// GENERATED MIRROR NOTE: this file is authoritative. Edge functions consume
// supabase/functions/_shared/salesEngine/quoteIntakeContract.ts, generated by
// scripts/sync-sales-engine-intake.mjs. Never edit the mirror directly.

export type RequirementCategory =
  | "required_to_price"
  | "required_by_current_product_policy"
  | "conditional_price_modifier"
  | "optional_addon"
  | "required_after_price_for_delivery"
  | "required_after_price_for_booking"
  | "manual_review_trigger"
  | "derived_from_verified_source"
  | "owner_decision_required"
  | "not_applicable";

export type IntakeStage = "service_selection" | "pre_price" | "post_price_delivery" | "post_price_booking";
export type ApprovalStatus = "approved_current_behavior" | "pending_ben_review" | "deprecated";
export type CanonicalServiceId =
  | "window_cleaning" | "partial_window_cleaning" | "window_promo_99"
  | "house_wash" | "gutter_cleaning" | "roof_cleaning"
  | "driveway_cleaning" | "pressure_washing" | "solar_panel_cleaning"
  | "screen_repair" | "commercial_window_bid";
export type CanonicalWindowSides = "outside_only" | "inside_and_outside";

export interface IntakeValues { [path: string]: unknown }
export interface CanonicalIntakeField {
  fieldId: string;
  storagePath: string;
  appliesToServices: readonly CanonicalServiceId[];
  stage: IntakeStage;
  category: RequirementCategory;
  requiredWhen: string;
  acceptedValues?: readonly (string | number)[] | string;
  normalization?: string;
  validation: string;
  pricingDestination?: string;
  changesPrice: boolean;
  recapRequired: boolean;
  verifiedValueAllowed: boolean;
  derivedValueAllowed: boolean;
  missingBehavior: "missing_information" | "manual_review" | "omit_modifier" | "block_delivery" | "block_booking" | "owner_decision";
  manualReviewBehavior?: string;
  approvalStatus: ApprovalStatus;
  legacyAliases?: readonly string[];
  deprecationNotes?: string;
}

const all = (...services: CanonicalServiceId[]) => services;
export const CANONICAL_INTAKE_FIELDS: readonly CanonicalIntakeField[] = [
  { fieldId:"services", storagePath:"services", appliesToServices:all("window_cleaning","partial_window_cleaning","window_promo_99","house_wash","gutter_cleaning","roof_cleaning","driveway_cleaning","pressure_washing","solar_panel_cleaning","screen_repair","commercial_window_bid"), stage:"service_selection", category:"required_to_price", requiredWhen:"always", acceptedValues:"canonical service id array", normalization:"normalizeServiceId; deduplicate", validation:"at least one supported service", pricingDestination:"additionalServices / promotion routing", changesPrice:true, recapRequired:true, verifiedValueAllowed:true, derivedValueAllowed:false, missingBehavior:"missing_information", approvalStatus:"approved_current_behavior" },
  { fieldId:"windowCleaningScope", storagePath:"windowCleaningScope", appliesToServices:all("window_cleaning","partial_window_cleaning","commercial_window_bid"), stage:"pre_price", category:"owner_decision_required", requiredWhen:"window request needs routing", acceptedValues:["whole_home","partial","commercial_custom"], validation:"enum", changesPrice:false, recapRequired:true, verifiedValueAllowed:true, derivedValueAllowed:false, missingBehavior:"owner_decision", approvalStatus:"pending_ben_review" },
  { fieldId:"windowCleaningSides", storagePath:"windowCleaningSides", appliesToServices:all("window_cleaning","partial_window_cleaning"), stage:"pre_price", category:"required_to_price", requiredWhen:"standard or partial window cleaning", acceptedValues:["outside_only","inside_and_outside"], normalization:"normalizeWindowCleaningSides", validation:"canonical enum; never default missing", pricingDestination:"homeDetails.windowCleaningType via windowSidesToPricingType", changesPrice:true, recapRequired:true, verifiedValueAllowed:true, derivedValueAllowed:false, missingBehavior:"missing_information", approvalStatus:"approved_current_behavior", legacyAliases:["windowCleaningType"], deprecationNotes:"windowCleaningType is read-only legacy input at boundaries; new progressive-session writes use windowCleaningSides." },
  { fieldId:"squareFootage", storagePath:"squareFootage", appliesToServices:all("window_cleaning","house_wash","gutter_cleaning","roof_cleaning"), stage:"pre_price", category:"required_to_price", requiredWhen:"an applicable square-foot service is selected", acceptedValues:"finite number > 0 and <= 100000", validation:"pricing-engine range", pricingDestination:"homeDetails.squareFootage", changesPrice:true, recapRequired:true, verifiedValueAllowed:true, derivedValueAllowed:true, missingBehavior:"missing_information", approvalStatus:"approved_current_behavior" },
  { fieldId:"stories", storagePath:"stories", appliesToServices:all("window_cleaning","house_wash","gutter_cleaning","roof_cleaning"), stage:"pre_price", category:"required_to_price", requiredWhen:"an applicable square-foot service is selected", acceptedValues:[1,2,3], validation:"enum", pricingDestination:"homeDetails.stories", changesPrice:true, recapRequired:true, verifiedValueAllowed:true, derivedValueAllowed:true, missingBehavior:"missing_information", approvalStatus:"approved_current_behavior" },
  { fieldId:"condition", storagePath:"condition", appliesToServices:all("window_cleaning"), stage:"pre_price", category:"required_by_current_product_policy", requiredWhen:"standard whole-home window cleaning", acceptedValues:["maintenance","heavy"], validation:"enum", pricingDestination:"homeDetails.condition", changesPrice:true, recapRequired:true, verifiedValueAllowed:true, derivedValueAllowed:false, missingBehavior:"missing_information", approvalStatus:"approved_current_behavior", legacyAliases:["windowCleaningCondition"] },
  ...(["hardWaterStains","frenchPanes","solarScreens","ladderWork","sunroom"] as const).map((fieldId): CanonicalIntakeField => ({ fieldId, storagePath:fieldId, appliesToServices:all("window_cleaning"), stage:"pre_price", category:"conditional_price_modifier", requiredWhen:"customer indicates applicable advanced window condition", validation:"existing web values", pricingDestination:`homeDetails.${fieldId}`, changesPrice:true, recapRequired:true, verifiedValueAllowed:true, derivedValueAllowed:false, missingBehavior:"omit_modifier", approvalStatus:"pending_ben_review" })),
  ...(["hardWaterPercent","frenchPanesPercent","solarScreensPercent"] as const).map((fieldId): CanonicalIntakeField => ({ fieldId, storagePath:fieldId, appliesToServices:all("window_cleaning"), stage:"pre_price", category:"conditional_price_modifier", requiredWhen:`${fieldId.replace("Percent", "")} is explicitly selected`, acceptedValues:"configured percentage range", validation:"finite configured percentage", pricingDestination:`homeDetails.${fieldId}`, changesPrice:true, recapRequired:true, verifiedValueAllowed:true, derivedValueAllowed:false, missingBehavior:"missing_information", approvalStatus:"pending_ben_review" })),
  { fieldId:"ladderWorkCount", storagePath:"ladderWorkCount", appliesToServices:all("window_cleaning"), stage:"pre_price", category:"conditional_price_modifier", requiredWhen:"ladderWork is explicitly selected", acceptedValues:"positive integer", validation:"positive integer", pricingDestination:"homeDetails.ladderWorkCount", changesPrice:true, recapRequired:true, verifiedValueAllowed:true, derivedValueAllowed:false, missingBehavior:"missing_information", approvalStatus:"pending_ben_review" },
  { fieldId:"windowCount", storagePath:"windowCount", appliesToServices:all("partial_window_cleaning","window_promo_99"), stage:"pre_price", category:"required_to_price", requiredWhen:"partial or promotion path selected", acceptedValues:"positive integer", validation:"positive integer plus configured promotion maximum", pricingDestination:"partial input or promotion.windowCount", changesPrice:true, recapRequired:true, verifiedValueAllowed:true, derivedValueAllowed:false, missingBehavior:"missing_information", approvalStatus:"approved_current_behavior" },
  { fieldId:"partialWindowPricingPolicy", storagePath:"humanPricingRequired", appliesToServices:all("partial_window_cleaning"), stage:"pre_price", category:"manual_review_trigger", requiredWhen:"partial-window request selected without an authoritative configured partial-price path", validation:"manual review", changesPrice:false, recapRequired:false, verifiedValueAllowed:false, derivedValueAllowed:false, missingBehavior:"manual_review", manualReviewBehavior:"must not enter whole-home square-footage pricing", approvalStatus:"approved_current_behavior" },
  { fieldId:"promotionId", storagePath:"promotionId", appliesToServices:all("window_promo_99"), stage:"pre_price", category:"required_to_price", requiredWhen:"promotion explicitly selected", acceptedValues:"active configured promotion id", validation:"live pricing configuration", pricingDestination:"promotion.id", changesPrice:true, recapRequired:true, verifiedValueAllowed:false, derivedValueAllowed:true, missingBehavior:"missing_information", approvalStatus:"approved_current_behavior" },
  { fieldId:"houseWashStainType", storagePath:"houseWashStainType", appliesToServices:all("house_wash"), stage:"pre_price", category:"conditional_price_modifier", requiredWhen:"rust/irrigation staining applies", acceptedValues:["organic","rust"], validation:"enum", pricingDestination:"additionalServices.houseWashDetails.stainType", changesPrice:true, recapRequired:true, verifiedValueAllowed:true, derivedValueAllowed:false, missingBehavior:"omit_modifier", approvalStatus:"approved_current_behavior" },
  { fieldId:"gutterUndergroundDrains", storagePath:"gutterAddons.undergroundDrains", appliesToServices:all("gutter_cleaning"), stage:"pre_price", category:"optional_addon", requiredWhen:"add-on selected; count then required", acceptedValues:["1","2","3","4+"], validation:"configured count bucket", pricingDestination:"additionalServices.gutterAddons.undergroundDrains", changesPrice:true, recapRequired:true, verifiedValueAllowed:true, derivedValueAllowed:false, missingBehavior:"missing_information", approvalStatus:"pending_ben_review" },
  { fieldId:"gutterMinorRepairs", storagePath:"gutterAddons.minorRepairs", appliesToServices:all("gutter_cleaning"), stage:"pre_price", category:"optional_addon", requiredWhen:"add-on selected", acceptedValues:["true","false"], validation:"boolean", pricingDestination:"additionalServices.gutterAddons.minorRepairs", changesPrice:true, recapRequired:true, verifiedValueAllowed:true, derivedValueAllowed:false, missingBehavior:"omit_modifier", approvalStatus:"pending_ben_review" },
  { fieldId:"gutterGuardsLinearFeet", storagePath:"gutterAddons.gutterGuards.linearFeet", appliesToServices:all("gutter_cleaning"), stage:"pre_price", category:"optional_addon", requiredWhen:"gutter guards selected", acceptedValues:"positive finite number", validation:"positive finite", pricingDestination:"additionalServices.gutterAddons.gutterGuards.linearFeet", changesPrice:true, recapRequired:true, verifiedValueAllowed:true, derivedValueAllowed:true, missingBehavior:"missing_information", approvalStatus:"pending_ben_review" },
  { fieldId:"roofType", storagePath:"roofType", appliesToServices:all("roof_cleaning"), stage:"pre_price", category:"owner_decision_required", requiredWhen:"roof cleaning selected", acceptedValues:["asphalt","tile","metal","flat"], validation:"enum", pricingDestination:"additionalServices.roofType", changesPrice:true, recapRequired:true, verifiedValueAllowed:true, derivedValueAllowed:true, missingBehavior:"owner_decision", approvalStatus:"pending_ben_review" },
  { fieldId:"roofSeverity", storagePath:"roofSeverity", appliesToServices:all("roof_cleaning"), stage:"pre_price", category:"owner_decision_required", requiredWhen:"roof cleaning selected", acceptedValues:["light","moderate","heavy"], validation:"enum", pricingDestination:"additionalServices.roofSeverity", changesPrice:true, recapRequired:true, verifiedValueAllowed:true, derivedValueAllowed:false, missingBehavior:"owner_decision", approvalStatus:"pending_ben_review" },
  { fieldId:"drivewaySqft", storagePath:"drivewaySqft", appliesToServices:all("driveway_cleaning"), stage:"pre_price", category:"required_to_price", requiredWhen:"driveway selected", acceptedValues:"positive finite number", validation:"positive finite", pricingDestination:"additionalServices.drivewayCleaning.sqft", changesPrice:true, recapRequired:true, verifiedValueAllowed:true, derivedValueAllowed:true, missingBehavior:"missing_information", approvalStatus:"approved_current_behavior" },
  { fieldId:"drivewaySurface", storagePath:"drivewaySurface", appliesToServices:all("driveway_cleaning"), stage:"pre_price", category:"required_to_price", requiredWhen:"driveway selected", acceptedValues:["concrete","stamped","pavers","brick","stone","tile"], validation:"enum", pricingDestination:"additionalServices.drivewayCleaning.surfaceType", changesPrice:true, recapRequired:true, verifiedValueAllowed:true, derivedValueAllowed:false, missingBehavior:"missing_information", approvalStatus:"approved_current_behavior" },
  { fieldId:"pressureWashingSurface", storagePath:"pressureWashSurface", appliesToServices:all("pressure_washing"), stage:"pre_price", category:"required_to_price", requiredWhen:"pressure washing selected", acceptedValues:["concrete","stamped","pavers","brick","stone","tile"], validation:"enum", pricingDestination:"additionalServices.pressureWashing.surfaceType", changesPrice:true, recapRequired:true, verifiedValueAllowed:true, derivedValueAllowed:false, missingBehavior:"missing_information", approvalStatus:"approved_current_behavior" },
  { fieldId:"pressureWashingAreas", storagePath:"pressureWashingAreas", appliesToServices:all("pressure_washing"), stage:"pre_price", category:"required_to_price", requiredWhen:"pressure washing selected", acceptedValues:"one or more enabled named areas with positive sqft", validation:"frontPorch/backPatio/poolDeck/walkways; at least one valid", pricingDestination:"additionalServices.pressureWashing named areas", changesPrice:true, recapRequired:true, verifiedValueAllowed:true, derivedValueAllowed:true, missingBehavior:"missing_information", manualReviewBehavior:"invalid enabled area is manual review in pricing engine", approvalStatus:"approved_current_behavior", legacyAliases:["pressureWashSqft"] },
  { fieldId:"solarPanelCount", storagePath:"solarPanelCount", appliesToServices:all("solar_panel_cleaning"), stage:"pre_price", category:"required_to_price", requiredWhen:"solar panel cleaning selected", acceptedValues:"integer 1..500", validation:"pricing-engine range", pricingDestination:"additionalServices.solarPanelCleaning.panelCount", changesPrice:true, recapRequired:true, verifiedValueAllowed:true, derivedValueAllowed:false, missingBehavior:"missing_information", approvalStatus:"approved_current_behavior" },
  { fieldId:"solarPanelPolicy", storagePath:"humanPricingRequired", appliesToServices:all("solar_panel_cleaning"), stage:"pre_price", category:"owner_decision_required", requiredWhen:"solar selected", validation:"explicit policy resolution", changesPrice:false, recapRequired:false, verifiedValueAllowed:false, derivedValueAllowed:false, missingBehavior:"owner_decision", manualReviewBehavior:"channel must not infer approval from engine firmness", approvalStatus:"pending_ben_review" },
  { fieldId:"screenRepairCount", storagePath:"screenRepairCount", appliesToServices:all("screen_repair"), stage:"pre_price", category:"required_to_price", requiredWhen:"screen repair selected", acceptedValues:"integer 1..500", validation:"pricing-engine range", pricingDestination:"additionalServices.screenRepair.screenCount", changesPrice:true, recapRequired:true, verifiedValueAllowed:true, derivedValueAllowed:false, missingBehavior:"missing_information", approvalStatus:"approved_current_behavior" },
  { fieldId:"screenRepairPolicy", storagePath:"humanPricingRequired", appliesToServices:all("screen_repair"), stage:"pre_price", category:"owner_decision_required", requiredWhen:"screen repair selected", validation:"explicit policy resolution", changesPrice:false, recapRequired:false, verifiedValueAllowed:false, derivedValueAllowed:false, missingBehavior:"owner_decision", manualReviewBehavior:"channel must not infer approval from engine firmness", approvalStatus:"pending_ben_review" },
  { fieldId:"commercialLocations", storagePath:"commercialLocations", appliesToServices:all("commercial_window_bid"), stage:"pre_price", category:"required_by_current_product_policy", requiredWhen:"commercial request", validation:"at least one structured location", changesPrice:false, recapRequired:true, verifiedValueAllowed:true, derivedValueAllowed:false, missingBehavior:"missing_information", approvalStatus:"approved_current_behavior" },
  { fieldId:"commercialPricingPolicy", storagePath:"humanPricingRequired", appliesToServices:all("commercial_window_bid"), stage:"pre_price", category:"manual_review_trigger", requiredWhen:"commercial request", validation:"manual review", changesPrice:false, recapRequired:false, verifiedValueAllowed:false, derivedValueAllowed:false, missingBehavior:"manual_review", manualReviewBehavior:"commercial requests remain outside automated residential pricing", approvalStatus:"approved_current_behavior" },
  { fieldId:"contact_email", storagePath:"email", appliesToServices:all("window_cleaning","partial_window_cleaning","window_promo_99","house_wash","gutter_cleaning","roof_cleaning","driveway_cleaning","pressure_washing","solar_panel_cleaning","screen_repair","commercial_window_bid"), stage:"post_price_delivery", category:"required_after_price_for_delivery", requiredWhen:"save/deliver or book", validation:"email", changesPrice:false, recapRequired:false, verifiedValueAllowed:true, derivedValueAllowed:false, missingBehavior:"block_delivery", approvalStatus:"approved_current_behavior" },
  { fieldId:"address", storagePath:"address", appliesToServices:all("window_cleaning","partial_window_cleaning","window_promo_99","house_wash","gutter_cleaning","roof_cleaning","driveway_cleaning","pressure_washing","solar_panel_cleaning","screen_repair","commercial_window_bid"), stage:"post_price_booking", category:"required_after_price_for_booking", requiredWhen:"availability or booking", validation:"authorized service address", changesPrice:false, recapRequired:false, verifiedValueAllowed:true, derivedValueAllowed:false, missingBehavior:"block_booking", approvalStatus:"approved_current_behavior" },
] as const;

const SERVICE_ALIASES: Readonly<Record<string, CanonicalServiceId>> = Object.freeze({
  windowCleaning:"window_cleaning", window_cleaning:"window_cleaning",
  houseWash:"house_wash", house_wash:"house_wash",
  gutters:"gutter_cleaning", gutterCleaning:"gutter_cleaning", gutter_cleaning:"gutter_cleaning",
  roofCleaning:"roof_cleaning", roof_cleaning:"roof_cleaning",
  driveway:"driveway_cleaning", drivewayCleaning:"driveway_cleaning", driveway_cleaning:"driveway_cleaning",
  pressureWashing:"pressure_washing", pressure_washing:"pressure_washing",
  solarPanelCleaning:"solar_panel_cleaning", solar_panel_cleaning:"solar_panel_cleaning",
  screenRepair:"screen_repair", screen_repair:"screen_repair",
});
export function normalizeServiceId(raw: string): CanonicalServiceId | null { return SERVICE_ALIASES[raw] ?? null; }
export function normalizeWindowCleaningSides(raw: unknown): CanonicalWindowSides | null {
  if (raw === "outside_only" || raw === "exterior") return "outside_only";
  if (raw === "inside_and_outside" || raw === "both") return "inside_and_outside";
  return null;
}
export function windowSidesToPricingType(sides: unknown): "exterior" | "both" | null {
  const normalized = normalizeWindowCleaningSides(sides);
  return normalized === "outside_only" ? "exterior" : normalized === "inside_and_outside" ? "both" : null;
}

function present(v: unknown): boolean { return v !== undefined && v !== null && v !== "" && (!Array.isArray(v) || v.length > 0); }
function valueAtPath(values: IntakeValues, path: string): unknown {
  return path.split(".").reduce<unknown>((current, key) =>
    current && typeof current === "object" ? (current as Record<string, unknown>)[key] : undefined, values);
}
function servicesFor(values: IntakeValues): CanonicalServiceId[] {
  if (values.windowCleaningScope === "partial") return ["partial_window_cleaning"];
  if (values.windowCleaningScope === "commercial_custom" || values.customerType === "commercial") return ["commercial_window_bid"];
  const out = ((values.services as string[] | undefined) ?? []).map(normalizeServiceId).filter((v): v is CanonicalServiceId => !!v);
  if (present(values.promotionId)) return ["window_promo_99"];
  return [...new Set(out)];
}
export interface IntakeEvaluation { services: CanonicalServiceId[]; requiredToPrice: string[]; productPolicyRequired: string[]; ownerDecisions: string[]; manualReview: string[]; deliveryRequired: string[]; bookingRequired: string[]; }
export function evaluateQuoteIntake(values: IntakeValues): IntakeEvaluation {
  const services = servicesFor(values);
  if (services.length === 0) return { services, requiredToPrice:["services"], productPolicyRequired:[], ownerDecisions:[], manualReview:[], deliveryRequired:[], bookingRequired:[] };
  const required = new Set<string>(); const policy = new Set<string>(); const decisions = new Set<string>(); const review = new Set<string>();
  for (const service of services) for (const f of CANONICAL_INTAKE_FIELDS) if (f.appliesToServices.includes(service)) {
    if (f.category === "required_to_price" && f.fieldId !== "services" && f.fieldId !== "windowCleaningSides" && !present(valueAtPath(values, f.storagePath))) required.add(f.fieldId);
    if (f.category === "required_by_current_product_policy" && !present(valueAtPath(values, f.storagePath))) policy.add(f.fieldId);
    if (f.category === "owner_decision_required" &&
      (f.fieldId.endsWith("Policy") || !present(valueAtPath(values, f.storagePath)))) decisions.add(f.fieldId);
    if (f.category === "manual_review_trigger") review.add(f.fieldId);
  }
  if ((services.includes("window_cleaning") || services.includes("partial_window_cleaning")) && !normalizeWindowCleaningSides(values.windowCleaningSides ?? values.windowCleaningType)) required.add("windowCleaningSides");
  if (services.includes("pressure_washing")) {
    const areas = values.pressureWashingAreas as Record<string,{enabled?:boolean;sqft?:number}> | undefined;
    const valid = areas && Object.values(areas).some(a => a?.enabled && Number.isFinite(a.sqft) && (a.sqft ?? 0) > 0);
    if (!valid) required.add("pressureWashingAreas");
  }
  if (services.includes("window_cleaning")) {
    if (values.hardWaterStains === true && !present(values.hardWaterPercent)) required.add("hardWaterPercent");
    if (values.frenchPanes === true && !present(values.frenchPanesPercent)) required.add("frenchPanesPercent");
    if (values.solarScreens === true && !present(values.solarScreensPercent)) required.add("solarScreensPercent");
    if (values.ladderWork === true && !present(values.ladderWorkCount)) required.add("ladderWorkCount");
  }
  if (services.includes("gutter_cleaning")) {
    const addons = values.gutterAddons as Record<string, unknown> | undefined;
    const drains = addons?.undergroundDrains as {enabled?:boolean;count?:unknown} | undefined;
    const guards = addons?.gutterGuards as {enabled?:boolean;linearFeet?:unknown} | undefined;
    if (drains?.enabled && !present(drains.count)) required.add("gutterUndergroundDrains");
    if (guards?.enabled && (typeof guards.linearFeet !== "number" || guards.linearFeet <= 0)) required.add("gutterGuardsLinearFeet");
  }
  return { services, requiredToPrice:[...required], productPolicyRequired:[...policy], ownerDecisions:[...decisions], manualReview:[...review], deliveryRequired:present(values.email)?[]:["contact_email"], bookingRequired:present(values.address)?[]:["address"] };
}
