// ============================================================================
// voiceAdapter.ts — provider-independent voice/LLM adapter.
//
// This module converts an OpenAI-compatible /v1/chat/completions request into
// an OrchestratorInput, calls runOrchestrator({ channel: "voice" }), and
// converts the OrchestratorResult back into an OpenAI-compatible response
// (either JSON or Server-Sent Events).
//
// It is completely provider-independent. Vapi, LiveKit, or any other
// telephony vendor can point their custom-LLM at this adapter as long as they
// speak the OpenAI chat-completions contract. This file MUST NOT import
// Vapi/CallRail/Twilio SDKs or hard-code provider-specific field names.
// ============================================================================
import type { SupabaseClient } from "https://esm.sh/@supabase/supabase-js@2";
import {
  runOrchestrator,
  type OrchestratorResult,
  type VoiceDisposition,
} from "./aiOrchestrator.ts";

/** Max accepted request body in bytes. Voice turns are short; anything
 *  substantially larger than this is either malformed or hostile. */
export const MAX_ADAPTER_REQUEST_BYTES = 32 * 1024;

/** Provider-independent action the transport layer should take next. */
export type AdapterAction =
  | { kind: "speak" }
  | { kind: "tool_result_speak" }
  | { kind: "request_transfer"; reason?: string }
  | { kind: "callback_captured"; callbackRequestId?: string }
  | { kind: "end_call"; reason?: string }
  | { kind: "safe_failure"; reasonCode: string }
  | { kind: "uncertain_pricing"; reason?: string }
  | { kind: "uncertain_scheduling"; reason?: string }
  | { kind: "post_call_sms_handoff"; reason?: string };

export function mapDispositionToAction(d: VoiceDisposition | null | undefined): AdapterAction {
  if (!d) return { kind: "safe_failure", reasonCode: "missing_disposition" };
  switch (d.type) {
    case "speak": return { kind: "speak" };
    case "tool_result_speak": return { kind: "tool_result_speak" };
    case "transfer_human": return { kind: "request_transfer", reason: d.reason };
    case "callback_confirmed": return { kind: "callback_captured", callbackRequestId: d.callbackRequestId };
    case "graceful_end": return { kind: "end_call", reason: d.reason };
    case "safe_failure": return { kind: "safe_failure", reasonCode: d.reasonCode };
    case "uncertain_pricing": return { kind: "uncertain_pricing", reason: d.reason };
    case "uncertain_scheduling": return { kind: "uncertain_scheduling", reason: d.reason };
    case "post_call_sms_handoff": return { kind: "post_call_sms_handoff", reason: d.reason };
    default:
      // Exhaustiveness guard — fail closed on unknown disposition rather than
      // guessing "speak".
      return { kind: "safe_failure", reasonCode: "unknown_disposition" };
  }
}

// ---------------------------------------------------------------------------
// Request parsing
// ---------------------------------------------------------------------------

export interface ChatMessage {
  role: "system" | "user" | "assistant" | "tool";
  content: string;
}

export interface ParsedAdapterRequest {
  /** Model name, if the provider sent one. Kept for logging only — the
   *  orchestrator picks its own model via AI_SCHEDULING_MODEL. */
  model?: string;
  messages: ChatMessage[];
  stream: boolean;
  /**
   * Synthetic session ID for correlating this HTTP turn with an in-progress
   * conversation. Provider call-metadata fields (Vapi call.id, CallRail id,
   * caller ANI, provider timestamps) are optional and NOT assumed to live at
   * any specific location in the request body until a captured live payload
   * proves otherwise. Callers may pass one via `x-bluladder-session-id` or an
   * OpenAI-compatible `user` field; otherwise the adapter generates a synthetic
   * per-request id that is explicitly labeled as synthetic in logs.
   */
  sessionId: string;
  /** True when sessionId was generated by the adapter (not caller-supplied). */
  sessionIdIsSynthetic: boolean;
}

export type AdapterRequestError =
  | { kind: "unsupported_method" }
  | { kind: "unsupported_content_type" }
  | { kind: "too_large" }
  | { kind: "malformed_json" }
  | { kind: "missing_messages" }
  | { kind: "empty_conversation" };

export async function parseAdapterRequest(
  req: Request,
): Promise<{ ok: true; value: ParsedAdapterRequest } | { ok: false; error: AdapterRequestError }> {
  if (req.method !== "POST") return { ok: false, error: { kind: "unsupported_method" } };
  const ct = (req.headers.get("content-type") || "").toLowerCase();
  if (!ct.includes("application/json")) return { ok: false, error: { kind: "unsupported_content_type" } };
  const raw = await req.text();
  if (raw.length > MAX_ADAPTER_REQUEST_BYTES) return { ok: false, error: { kind: "too_large" } };
  let body: any;
  try {
    body = JSON.parse(raw);
  } catch {
    return { ok: false, error: { kind: "malformed_json" } };
  }
  if (!body || !Array.isArray(body.messages)) return { ok: false, error: { kind: "missing_messages" } };
  const messages: ChatMessage[] = [];
  for (const m of body.messages) {
    if (!m || typeof m !== "object") continue;
    const role = m.role;
    const content = typeof m.content === "string" ? m.content : "";
    if (role !== "system" && role !== "user" && role !== "assistant" && role !== "tool") continue;
    messages.push({ role, content });
  }
  const hasUser = messages.some((m) => m.role === "user" && m.content.trim().length > 0);
  if (!hasUser) return { ok: false, error: { kind: "empty_conversation" } };

  const headerSession = req.headers.get("x-bluladder-session-id");
  const userField = typeof body.user === "string" ? body.user : "";
  const suppliedSession = headerSession || userField || "";
  const sessionIdIsSynthetic = !suppliedSession;
  const sessionId = suppliedSession || `synthetic-${crypto.randomUUID()}`;

  return {
    ok: true,
    value: {
      model: typeof body.model === "string" ? body.model : undefined,
      messages,
      stream: body.stream === true,
      sessionId,
      sessionIdIsSynthetic,
    },
  };
}

// ---------------------------------------------------------------------------
// Response building
// ---------------------------------------------------------------------------

export interface AdapterCompletion {
  content: string;
  action: AdapterAction;
  orchestrator: OrchestratorResult;
}

/**
 * Split the orchestrator reply into small chunks so an SSE consumer sees the
 * reply progressively. This is a pragmatic streaming implementation — the
 * upstream orchestrator does not currently expose a token stream. Callers
 * treat this as a valid OpenAI-compatible chat.completion.chunk sequence.
 */
export function chunkReply(reply: string, chunkSize = 80): string[] {
  const out: string[] = [];
  const s = reply || "";
  for (let i = 0; i < s.length; i += chunkSize) out.push(s.slice(i, i + chunkSize));
  return out.length ? out : [""];
}

export function buildNonStreamingResponse(model: string, completion: AdapterCompletion): Response {
  const body = {
    id: `chatcmpl-${crypto.randomUUID()}`,
    object: "chat.completion",
    created: Math.floor(Date.now() / 1000),
    model,
    choices: [
      {
        index: 0,
        message: { role: "assistant", content: completion.content },
        finish_reason: "stop",
      },
    ],
    bluladder: {
      action: completion.action,
      state: completion.orchestrator.state ?? null,
    },
  };
  return new Response(JSON.stringify(body), {
    status: 200,
    headers: { "Content-Type": "application/json" },
  });
}

export function buildStreamingResponse(model: string, completion: AdapterCompletion): Response {
  const encoder = new TextEncoder();
  const id = `chatcmpl-${crypto.randomUUID()}`;
  const created = Math.floor(Date.now() / 1000);
  const chunks = chunkReply(completion.content);
  const stream = new ReadableStream<Uint8Array>({
    start(controller) {
      const write = (obj: unknown) => controller.enqueue(encoder.encode(`data: ${JSON.stringify(obj)}\n\n`));
      // Initial role chunk (OpenAI convention).
      write({
        id, object: "chat.completion.chunk", created, model,
        choices: [{ index: 0, delta: { role: "assistant" }, finish_reason: null }],
      });
      for (const c of chunks) {
        write({
          id, object: "chat.completion.chunk", created, model,
          choices: [{ index: 0, delta: { content: c }, finish_reason: null }],
        });
      }
      // Final chunk with finish_reason + BluLadder disposition.
      write({
        id, object: "chat.completion.chunk", created, model,
        choices: [{ index: 0, delta: {}, finish_reason: "stop" }],
        bluladder: { action: completion.action, state: completion.orchestrator.state ?? null },
      });
      // Required OpenAI SSE terminator.
      controller.enqueue(encoder.encode(`data: [DONE]\n\n`));
      controller.close();
    },
  });
  return new Response(stream, {
    status: 200,
    headers: {
      "Content-Type": "text/event-stream; charset=utf-8",
      "Cache-Control": "no-cache, no-transform",
      "Connection": "keep-alive",
    },
  });
}

// ---------------------------------------------------------------------------
// Orchestration entrypoint
// ---------------------------------------------------------------------------

export async function runVoiceAdapter(args: {
  supabase: SupabaseClient;
  request: ParsedAdapterRequest;
  /** Conversation-store id. Callers may pass one for continuity; if absent,
   *  the adapter uses the synthetic sessionId. This never crosses back to the
   *  language model — it is a server-side handle only. */
  conversationId?: string;
  /** Session token forwarded to tools that require it. In this offline slice
   *  the caller may pass an empty string. */
  sessionToken?: string;
}): Promise<AdapterCompletion> {
  const { supabase, request } = args;
  const conversationId = args.conversationId || request.sessionId;
  const sessionToken = args.sessionToken || "";
  // Build history from all but the final user message; pass the final user
  // message separately per the orchestrator contract.
  const nonSystem = request.messages.filter((m) => m.role !== "system" && m.role !== "tool");
  const lastUserIdx = (() => {
    for (let i = nonSystem.length - 1; i >= 0; i--) if (nonSystem[i].role === "user") return i;
    return -1;
  })();
  const history = lastUserIdx >= 0
    ? nonSystem.slice(0, lastUserIdx).map((m) => ({ role: m.role as "user" | "assistant", content: m.content }))
    : [];
  const userMessage = lastUserIdx >= 0 ? nonSystem[lastUserIdx].content : "";
  try {
    const orchestrator = await runOrchestrator({
      supabase,
      conversationId,
      sessionToken,
      channel: "voice",
      history,
      userMessage,
    });
    const action = mapDispositionToAction(orchestrator.voice);
    return { content: orchestrator.reply, action, orchestrator };
  } catch (_err) {
    // Fail closed. The transport layer will surface a safe_failure to the
    // provider so the call is not left in an undefined state.
    return {
      content: "Sorry, I hit a snag. Let me get a teammate to reach out.",
      action: { kind: "safe_failure", reasonCode: "orchestrator_exception" },
      orchestrator: {
        reply: "",
        toolEvents: [],
        events: [],
        state: "error_recovery",
        error: "orchestrator_exception",
        voice: { type: "safe_failure", reasonCode: "orchestrator_exception" },
      },
    };
  }
}