// ============================================================================
// voiceAdapter.ts — provider-independent voice/LLM adapter.
//
// This module converts an OpenAI-compatible /v1/chat/completions request into
// an OrchestratorInput, calls runOrchestrator({ channel: "voice" }), and
// converts the OrchestratorResult back into an OpenAI-compatible response
// (either JSON or Server-Sent Events).
//
// It is completely provider-independent. Vapi, LiveKit, or any other
// telephony vendor can point their custom-LLM at this adapter as long as they
// speak the OpenAI chat-completions contract. This file MUST NOT import
// Vapi/CallRail/Twilio SDKs or hard-code provider-specific field names.
// ============================================================================
import type { SupabaseClient } from "https://esm.sh/@supabase/supabase-js@2";
import {
  runOrchestrator,
  streamKnowledgeReply,
  buildVoiceSystemPrompt,
  type OrchestratorResult,
  type VoiceDisposition,
} from "./aiOrchestrator.ts";
import {
  classifyVoiceRoute,
  slowBranchAcknowledgement,
  stripVoiceControlTags,
  FLUSH_TAG,
  type VoiceRoute,
} from "./voiceFastPath.ts";
import { makeClock, sessionHash, voiceLatencyEnabled, type VoiceLatencyEvent } from "./voiceLatencyMetrics.ts";
import { BUILD_ID } from "./buildMarker.ts";

/** Max accepted request body in bytes. Voice turns are short; anything
 *  substantially larger than this is either malformed or hostile. */
export const MAX_ADAPTER_REQUEST_BYTES = 32 * 1024;

/** Provider-independent action the transport layer should take next. */
export type AdapterAction =
  | { kind: "speak" }
  | { kind: "tool_result_speak" }
  | { kind: "request_transfer"; reason?: string }
  | { kind: "callback_captured"; callbackRequestId?: string }
  | { kind: "end_call"; reason?: string }
  | { kind: "safe_failure"; reasonCode: string }
  | { kind: "uncertain_pricing"; reason?: string }
  | { kind: "uncertain_scheduling"; reason?: string }
  | { kind: "post_call_sms_handoff"; reason?: string };

export function mapDispositionToAction(d: VoiceDisposition | null | undefined): AdapterAction {
  if (!d) return { kind: "safe_failure", reasonCode: "missing_disposition" };
  switch (d.type) {
    case "speak": return { kind: "speak" };
    case "tool_result_speak": return { kind: "tool_result_speak" };
    case "transfer_human": return { kind: "request_transfer", reason: d.reason };
    case "callback_confirmed": return { kind: "callback_captured", callbackRequestId: d.callbackRequestId };
    case "graceful_end": return { kind: "end_call", reason: d.reason };
    case "safe_failure": return { kind: "safe_failure", reasonCode: d.reasonCode };
    case "uncertain_pricing": return { kind: "uncertain_pricing", reason: d.reason };
    case "uncertain_scheduling": return { kind: "uncertain_scheduling", reason: d.reason };
    case "post_call_sms_handoff": return { kind: "post_call_sms_handoff", reason: d.reason };
    default:
      // Exhaustiveness guard — fail closed on unknown disposition rather than
      // guessing "speak".
      return { kind: "safe_failure", reasonCode: "unknown_disposition" };
  }
}

// ---------------------------------------------------------------------------
// Request parsing
// ---------------------------------------------------------------------------

export interface ChatMessage {
  role: "system" | "user" | "assistant" | "tool";
  content: string;
}

export interface ParsedAdapterRequest {
  /** Model name, if the provider sent one. Kept for logging only — the
   *  orchestrator picks its own model via AI_SCHEDULING_MODEL. */
  model?: string;
  messages: ChatMessage[];
  stream: boolean;
  /**
   * Synthetic session ID for correlating this HTTP turn with an in-progress
   * conversation. Provider call-metadata fields (Vapi call.id, CallRail id,
   * caller ANI, provider timestamps) are optional and NOT assumed to live at
   * any specific location in the request body until a captured live payload
   * proves otherwise. Callers may pass one via `x-bluladder-session-id` or an
   * OpenAI-compatible `user` field; otherwise the adapter generates a synthetic
   * per-request id that is explicitly labeled as synthetic in logs.
   */
  sessionId: string;
  /** True when sessionId was generated by the adapter (not caller-supplied). */
  sessionIdIsSynthetic: boolean;
}

export type AdapterRequestError =
  | { kind: "unsupported_method" }
  | { kind: "unsupported_content_type" }
  | { kind: "too_large" }
  | { kind: "malformed_json" }
  | { kind: "missing_messages" }
  | { kind: "empty_conversation" };

export async function parseAdapterRequest(
  req: Request,
): Promise<{ ok: true; value: ParsedAdapterRequest } | { ok: false; error: AdapterRequestError }> {
  if (req.method !== "POST") return { ok: false, error: { kind: "unsupported_method" } };
  const ct = (req.headers.get("content-type") || "").toLowerCase();
  if (!ct.includes("application/json")) return { ok: false, error: { kind: "unsupported_content_type" } };
  const raw = await req.text();
  if (raw.length > MAX_ADAPTER_REQUEST_BYTES) return { ok: false, error: { kind: "too_large" } };
  let body: any;
  try {
    body = JSON.parse(raw);
  } catch {
    return { ok: false, error: { kind: "malformed_json" } };
  }
  if (!body || !Array.isArray(body.messages)) return { ok: false, error: { kind: "missing_messages" } };
  const messages: ChatMessage[] = [];
  for (const m of body.messages) {
    if (!m || typeof m !== "object") continue;
    const role = m.role;
    const content = typeof m.content === "string" ? m.content : "";
    if (role !== "system" && role !== "user" && role !== "assistant" && role !== "tool") continue;
    messages.push({ role, content });
  }
  const hasUser = messages.some((m) => m.role === "user" && m.content.trim().length > 0);
  if (!hasUser) return { ok: false, error: { kind: "empty_conversation" } };

  const headerSession = req.headers.get("x-bluladder-session-id");
  const userField = typeof body.user === "string" ? body.user : "";
  const suppliedSession = headerSession || userField || "";
  const sessionIdIsSynthetic = !suppliedSession;
  const sessionId = suppliedSession || `synthetic-${crypto.randomUUID()}`;

  return {
    ok: true,
    value: {
      model: typeof body.model === "string" ? body.model : undefined,
      messages,
      stream: body.stream === true,
      sessionId,
      sessionIdIsSynthetic,
    },
  };
}

// ---------------------------------------------------------------------------
// Response building
// ---------------------------------------------------------------------------

export interface AdapterCompletion {
  content: string;
  action: AdapterAction;
  orchestrator: OrchestratorResult;
}

/**
 * Split the orchestrator reply into small chunks so an SSE consumer sees the
 * reply progressively. This is a pragmatic streaming implementation — the
 * upstream orchestrator does not currently expose a token stream. Callers
 * treat this as a valid OpenAI-compatible chat.completion.chunk sequence.
 */
export function chunkReply(reply: string, chunkSize = 80): string[] {
  const out: string[] = [];
  const s = reply || "";
  for (let i = 0; i < s.length; i += chunkSize) out.push(s.slice(i, i + chunkSize));
  return out.length ? out : [""];
}

// ---------------------------------------------------------------------------
// Streaming adapter events. These are BluLadder-internal events; the transport
// layer converts them into OpenAI-compatible chat.completion.chunk SSE frames.
// ---------------------------------------------------------------------------
export type VoiceStreamEvent =
  | { type: "route"; route: VoiceRoute }
  | { type: "role_delta" }
  | { type: "text_delta"; text: string }
  | { type: "acknowledgement"; text: string }
  | { type: "tool_started"; tool: string }
  | { type: "tool_completed"; tool: string }
  | { type: "disposition"; disposition: VoiceDisposition | null }
  | { type: "complete"; result: OrchestratorResult }
  | { type: "error"; reasonCode: string };

export interface VoiceStreamArgs {
  supabase: SupabaseClient;
  request: ParsedAdapterRequest;
  conversationId?: string;
  sessionToken?: string;
  /** Called at each event. Return false to abort (transport disconnected). */
  emit: (ev: VoiceStreamEvent) => void | boolean | Promise<void | boolean>;
}

export async function ensureVoiceConversation(args: {
  supabase: SupabaseClient;
  request: ParsedAdapterRequest;
  conversationId?: string;
  sessionToken?: string;
}): Promise<{ conversationId: string; sessionToken: string }> {
  const { supabase, request } = args;
  const sessionToken = args.sessionToken || request.sessionId;

  if (args.conversationId) {
    const { data: existing } = await supabase
      .from("chat_conversations")
      .select("id, session_token")
      .eq("id", args.conversationId)
      .maybeSingle();
    if (existing?.id) return { conversationId: existing.id, sessionToken: existing.session_token || sessionToken };

    const { data: inserted } = await supabase
      .from("chat_conversations")
      .insert({ id: args.conversationId, session_token: sessionToken, channel: "voice" })
      .select("id, session_token")
      .single();
    if (inserted?.id) return { conversationId: inserted.id, sessionToken: inserted.session_token || sessionToken };
    return { conversationId: args.conversationId, sessionToken };
  }

  const { data: existing } = await supabase
    .from("chat_conversations")
    .select("id, session_token")
    .eq("session_token", sessionToken)
    .eq("channel", "voice")
    .order("created_at", { ascending: false })
    .limit(1)
    .maybeSingle();
  if (existing?.id) return { conversationId: existing.id, sessionToken: existing.session_token || sessionToken };

  const { data: inserted } = await supabase
    .from("chat_conversations")
    .insert({ session_token: sessionToken, channel: "voice" })
    .select("id, session_token")
    .single();
  if (inserted?.id) return { conversationId: inserted.id, sessionToken: inserted.session_token || sessionToken };

  return { conversationId: request.sessionId, sessionToken };
}

/** True streaming voice run.
 *
 *  Fast knowledge lane: streams model tokens directly, emitting text_delta
 *  events as they arrive from the AI gateway. This is real first-token
 *  streaming and is the primary source of the latency improvement.
 *
 *  Full-orchestrator lane: emits a deterministic acknowledgement immediately
 *  (followed by <flush /> so the provider speaks it right away), then awaits
 *  runOrchestrator() and emits the final reply. Tool-loop turns cannot stream
 *  underlying model tokens because tool_calls require the full completion. */
export async function runVoiceAdapterStream(args: VoiceStreamArgs): Promise<{
  content: string;
  action: AdapterAction;
  orchestrator: OrchestratorResult;
  route: VoiceRoute;
  ackEmitted: boolean;
}> {
  const { supabase, request, emit } = args;
  const identity = await ensureVoiceConversation(args);
  const conversationId = identity.conversationId;
  const sessionToken = identity.sessionToken;
  const clock = makeClock();
  const t0 = clock.mark();
  const timings: VoiceLatencyEvent["t"] = { requestReceived: 0 };
  const emitEv = async (ev: VoiceStreamEvent) => { try { await emit(ev); } catch { /* transport */ } };

  // Extract last user message + history exactly as the non-streaming path does.
  const nonSystem = request.messages.filter((m) => m.role !== "system" && m.role !== "tool");
  let lastUserIdx = -1;
  for (let i = nonSystem.length - 1; i >= 0; i--) if (nonSystem[i].role === "user") { lastUserIdx = i; break; }
  const history = lastUserIdx >= 0
    ? nonSystem.slice(0, lastUserIdx).map((m) => ({ role: m.role as "user" | "assistant", content: m.content }))
    : [];
  const userMessage = lastUserIdx >= 0 ? nonSystem[lastUserIdx].content : "";

  const route = classifyVoiceRoute(userMessage);
  await emitEv({ type: "route", route });
  await emitEv({ type: "role_delta" });
  timings.firstRoleDelta = clock.since(t0);

  let ackEmitted = false;
  let accumulated = "";
  let orchestrator: OrchestratorResult | null = null;

  if (route.type === "fast_knowledge") {
    // Stream directly from the gateway using the SAME authoritative system
    // prompt (plus voice-response contract). No tools are exposed here.
    try {
      // Use empty facts / neutral state for the knowledge lane; if the model
      // decides the answer needs business data, fall-closed guidance in the
      // prompt keeps it from inventing.
      const system = await buildVoiceSystemPrompt(supabase, "new", {} as any);
      timings.modelRequestStarted = clock.since(t0);
      for await (const chunk of streamKnowledgeReply(system, userMessage, history)) {
        if (chunk.kind === "error") {
          // Fall through to full orchestrator on any error.
          break;
        }
        if (timings.firstModelToken === undefined) timings.firstModelToken = clock.since(t0);
        if (timings.firstContentDelta === undefined) timings.firstContentDelta = clock.since(t0);
        accumulated += chunk.text;
        await emitEv({ type: "text_delta", text: chunk.text });
      }
    } catch { /* fall through to full path */ }
    if (accumulated.trim().length === 0) {
      // Fast-path yielded nothing (auth/env/error). Fall to full orchestrator.
      orchestrator = await runOrchestrator({ supabase, conversationId, sessionToken, channel: "voice", history, userMessage });
      accumulated = orchestrator.reply;
      await emitEv({ type: "text_delta", text: accumulated });
    } else {
      // Synthesize a minimal OrchestratorResult so the transport layer still
      // has a disposition to work with. The fast lane never invokes tools.
      orchestrator = {
        reply: accumulated,
        toolEvents: [],
        events: ["voice_fast_path"],
        state: "new",
        voice: { type: "speak" },
      };
    }
    timings.orchestratorCompleted = clock.since(t0);
  } else {
    // Slow lane: emit deterministic acknowledgement (with <flush /> so the
    // TTS provider speaks it immediately), then run full orchestrator.
    const ack = slowBranchAcknowledgement(route.reason);
    if (ack) {
      const delta = `${ack} ${FLUSH_TAG} `;
      ackEmitted = true;
      await emitEv({ type: "acknowledgement", text: ack });
      await emitEv({ type: "text_delta", text: delta });
      if (timings.firstContentDelta === undefined) timings.firstContentDelta = clock.since(t0);
    }
    timings.orchestratorInvoked = clock.since(t0);
    orchestrator = await runOrchestrator({ supabase, conversationId, sessionToken, channel: "voice", history, userMessage });
    timings.orchestratorCompleted = clock.since(t0);
    // The final reply follows the acknowledgement. If the ack accidentally
    // duplicates the opening of the orchestrator's reply, avoid saying it
    // twice.
    let finalReply = orchestrator.reply || "";
    if (ack && finalReply.trim().toLowerCase().startsWith(ack.trim().toLowerCase())) {
      finalReply = finalReply.slice(ack.length).replace(/^[\s,.:;-]+/, "");
    }
    accumulated = ack ? `${ack} ${finalReply}` : finalReply;
    if (finalReply) await emitEv({ type: "text_delta", text: finalReply });
  }

  const disposition = orchestrator?.voice ?? null;
  await emitEv({ type: "disposition", disposition });
  if (orchestrator) await emitEv({ type: "complete", result: orchestrator });
  timings.finalSseEvent = clock.since(t0);
  timings.total = timings.finalSseEvent;

  // Sanitized latency log (feature-flagged; never emits content or PII).
  if (voiceLatencyEnabled()) {
    try {
      const hash = await sessionHash(request.sessionId);
      const ev: VoiceLatencyEvent = {
        at: "voice-latency",
        sessionHash: hash,
        channel: "voice",
        route: route.type === "fast_knowledge" ? "fast_knowledge" : "full_orchestrator",
        intentCategory: route.type === "fast_knowledge" ? route.category : route.reason,
        ackEmitted,
        toolInvoked: (orchestrator?.toolEvents?.length ?? 0) > 0,
        dispositionType: disposition?.type ?? null,
        errorCategory: orchestrator?.error ?? null,
        t: timings,
      };
      console.log(JSON.stringify(ev));
    } catch { /* never throw from telemetry */ }
  }

  const action = mapDispositionToAction(disposition);
  // Persisted / analytics text MUST NOT contain SSE flush/break tags.
  const cleanContent = stripVoiceControlTags(accumulated);
  const cleanResult: OrchestratorResult = orchestrator
    ? { ...orchestrator, reply: stripVoiceControlTags(orchestrator.reply || "") }
    : { reply: cleanContent, toolEvents: [], events: [], state: "new", voice: null };
  return { content: cleanContent, action, orchestrator: cleanResult, route, ackEmitted };
}

export function buildNonStreamingResponse(model: string, completion: AdapterCompletion): Response {
  const body = {
    id: `chatcmpl-${crypto.randomUUID()}`,
    object: "chat.completion",
    created: Math.floor(Date.now() / 1000),
    model,
    choices: [
      {
        index: 0,
        message: { role: "assistant", content: completion.content },
        finish_reason: "stop",
      },
    ],
    bluladder: {
      buildId: BUILD_ID,
      action: completion.action,
      state: completion.orchestrator.state ?? null,
    },
  };
  return new Response(JSON.stringify(body), {
    status: 200,
    headers: { "Content-Type": "application/json" },
  });
}

export function buildStreamingResponse(model: string, completion: AdapterCompletion): Response {
  const encoder = new TextEncoder();
  const id = `chatcmpl-${crypto.randomUUID()}`;
  const created = Math.floor(Date.now() / 1000);
  const chunks = chunkReply(completion.content);
  const stream = new ReadableStream<Uint8Array>({
    start(controller) {
      const write = (obj: unknown) => controller.enqueue(encoder.encode(`data: ${JSON.stringify(obj)}\n\n`));
      // Initial role chunk (OpenAI convention).
      write({
        id, object: "chat.completion.chunk", created, model,
        choices: [{ index: 0, delta: { role: "assistant" }, finish_reason: null }],
      });
      for (const c of chunks) {
        write({
          id, object: "chat.completion.chunk", created, model,
          choices: [{ index: 0, delta: { content: c }, finish_reason: null }],
        });
      }
      // Final chunk with finish_reason + BluLadder disposition.
      write({
        id, object: "chat.completion.chunk", created, model,
        choices: [{ index: 0, delta: {}, finish_reason: "stop" }],
        bluladder: { action: completion.action, state: completion.orchestrator.state ?? null },
      });
      // Required OpenAI SSE terminator.
      controller.enqueue(encoder.encode(`data: [DONE]\n\n`));
      controller.close();
    },
  });
  return new Response(stream, {
    status: 200,
    headers: {
      "Content-Type": "text/event-stream; charset=utf-8",
      "Cache-Control": "no-cache, no-transform",
      "Connection": "keep-alive",
    },
  });
}

// ---------------------------------------------------------------------------
// Orchestration entrypoint
// ---------------------------------------------------------------------------

export async function runVoiceAdapter(args: {
  supabase: SupabaseClient;
  request: ParsedAdapterRequest;
  /** Conversation-store id. Callers may pass one for continuity; if absent,
   *  the adapter uses the synthetic sessionId. This never crosses back to the
   *  language model — it is a server-side handle only. */
  conversationId?: string;
  /** Session token forwarded to tools that require it. In this offline slice
   *  the caller may pass an empty string. */
  sessionToken?: string;
}): Promise<AdapterCompletion> {
  const { supabase, request } = args;
  const identity = await ensureVoiceConversation(args);
  const conversationId = identity.conversationId;
  const sessionToken = identity.sessionToken;
  // Build history from all but the final user message; pass the final user
  // message separately per the orchestrator contract.
  const nonSystem = request.messages.filter((m) => m.role !== "system" && m.role !== "tool");
  const lastUserIdx = (() => {
    for (let i = nonSystem.length - 1; i >= 0; i--) if (nonSystem[i].role === "user") return i;
    return -1;
  })();
  const history = lastUserIdx >= 0
    ? nonSystem.slice(0, lastUserIdx).map((m) => ({ role: m.role as "user" | "assistant", content: m.content }))
    : [];
  const userMessage = lastUserIdx >= 0 ? nonSystem[lastUserIdx].content : "";
  try {
    const orchestrator = await runOrchestrator({
      supabase,
      conversationId,
      sessionToken,
      channel: "voice",
      history,
      userMessage,
    });
    const action = mapDispositionToAction(orchestrator.voice);
    return { content: orchestrator.reply, action, orchestrator };
  } catch (_err) {
    // Fail closed. The transport layer will surface a safe_failure to the
    // provider so the call is not left in an undefined state.
    return {
      content: "Sorry, I hit a snag. Let me get a teammate to reach out.",
      action: { kind: "safe_failure", reasonCode: "orchestrator_exception" },
      orchestrator: {
        reply: "",
        toolEvents: [],
        events: [],
        state: "error_recovery",
        error: "orchestrator_exception",
        voice: { type: "safe_failure", reasonCode: "orchestrator_exception" },
      },
    };
  }
}