// GENERATED MIRROR NOTE: this file is authoritative. Edge functions consume
// supabase/functions/_shared/salesEngine/quoteIntakeContract.ts, generated by
// scripts/sync-sales-engine-intake.mjs. Never edit the mirror directly.

export type RequirementCategory =
  | "required_to_price"
  | "required_by_current_product_policy"
  | "conditional_price_modifier"
  | "optional_addon"
  | "required_after_price_for_delivery"
  | "required_after_price_for_booking"
  | "manual_review_trigger"
  | "derived_from_verified_source"
  | "owner_decision_required"
  | "not_applicable";

export type IntakeStage = "service_selection" | "pre_price" | "post_price_delivery" | "post_price_booking";
export type ApprovalStatus =
  | "approved_current_behavior"
  | "confirmed_owner_rule"
  | "pending_ben_review"
  | "deprecated";
export type MissingBehavior =
  | "missing_information"
  | "missing_information_for_addon"
  | "manual_review"
  | "clarification"
  | "omit_modifier"
  | "omit_addon"
  | "block_delivery"
  | "block_booking"
  | "owner_decision"
  | "derive_from_selected_services"
  | "never_write_new";
export type CanonicalServiceId =
  | "window_cleaning" | "partial_window_cleaning" | "window_promo_99"
  | "house_wash" | "gutter_cleaning" | "roof_cleaning"
  | "driveway_cleaning" | "pressure_washing" | "solar_panel_cleaning"
  | "screen_repair" | "commercial_window_bid";
export type CanonicalWindowSides = "outside_only" | "inside_and_outside";

export interface IntakeValues { [path: string]: unknown }
export interface CanonicalIntakeField {
  fieldId: string;
  storagePath: string;
  appliesToServices: readonly CanonicalServiceId[];
  stage: IntakeStage;
  category: RequirementCategory;
  requiredWhen: string;
  acceptedValues?: readonly (string | number | boolean)[] | string;
  normalization?: string;
  validation: string;
  pricingDestination?: string;
  changesPrice: boolean;
  recapRequired: boolean;
  verifiedValueAllowed: boolean;
  derivedValueAllowed: boolean;
  missingBehavior: MissingBehavior;
  manualReviewBehavior?: string;
  approvalStatus: ApprovalStatus;
  legacyAliases?: readonly string[];
  deprecationNotes?: string;
  canonicalPrompt?: string;
  explanatoryCopy?: string;
  disclosure?: string;
}

const all = (...services: CanonicalServiceId[]) => services;
export const CANONICAL_QUOTE_RULE_IDS = Object.freeze({
  screenedEnclosureSoftWash: "screened_enclosure_soft_wash",
  enclosureWindowCleaning: "enclosure_window_cleaning",
  noScreenDiscount: "window_no_screen_discount",
  solarScreenService: "window_solar_screen_service",
  undergroundDrainClearing: "underground_gutter_drain_clearing",
  minorGutterRepairs: "minor_gutter_downspout_repairs",
  houseWashFrontPatio: "house_wash_front_patio",
  houseWashBackPatio: "house_wash_back_patio",
  houseWashWindowBundle: "house_wash_window_cleaning_bundle",
} as const);

export const CANONICAL_INTAKE_FIELDS: readonly CanonicalIntakeField[] = [
  { fieldId:"services", storagePath:"services", appliesToServices:all("window_cleaning","partial_window_cleaning","window_promo_99","house_wash","gutter_cleaning","roof_cleaning","driveway_cleaning","pressure_washing","solar_panel_cleaning","screen_repair","commercial_window_bid"), stage:"service_selection", category:"required_to_price", requiredWhen:"always", acceptedValues:"canonical service id array", normalization:"normalizeServiceId; deduplicate", validation:"at least one supported service", pricingDestination:"additionalServices / promotion routing", changesPrice:true, recapRequired:true, verifiedValueAllowed:true, derivedValueAllowed:false, missingBehavior:"missing_information", approvalStatus:"approved_current_behavior" },
  { fieldId:"windowCleaningScope", storagePath:"windowCleaningScope", appliesToServices:all("window_cleaning","partial_window_cleaning","commercial_window_bid"), stage:"pre_price", category:"owner_decision_required", requiredWhen:"window request needs routing", acceptedValues:["whole_home","partial","commercial_custom"], validation:"enum", changesPrice:false, recapRequired:true, verifiedValueAllowed:true, derivedValueAllowed:false, missingBehavior:"owner_decision", approvalStatus:"pending_ben_review" },
  { fieldId:"windowCleaningSides", storagePath:"windowCleaningSides", appliesToServices:all("window_cleaning","partial_window_cleaning"), stage:"pre_price", category:"required_to_price", requiredWhen:"standard or partial window cleaning", acceptedValues:["outside_only","inside_and_outside"], normalization:"normalizeWindowCleaningSides", validation:"canonical enum; never default missing", pricingDestination:"homeDetails.windowCleaningType via windowSidesToPricingType", changesPrice:true, recapRequired:true, verifiedValueAllowed:true, derivedValueAllowed:false, missingBehavior:"missing_information", approvalStatus:"approved_current_behavior", legacyAliases:["windowCleaningType"], deprecationNotes:"windowCleaningType is read-only legacy input at boundaries; new progressive-session writes use windowCleaningSides." },
  { fieldId:"squareFootage", storagePath:"squareFootage", appliesToServices:all("window_cleaning","house_wash","gutter_cleaning","roof_cleaning"), stage:"pre_price", category:"required_to_price", requiredWhen:"an applicable square-foot service is selected", acceptedValues:"finite number > 0 and <= 100000", validation:"pricing-engine range", pricingDestination:"homeDetails.squareFootage", changesPrice:true, recapRequired:true, verifiedValueAllowed:true, derivedValueAllowed:true, missingBehavior:"missing_information", approvalStatus:"approved_current_behavior" },
  { fieldId:"stories", storagePath:"stories", appliesToServices:all("window_cleaning","house_wash","gutter_cleaning","roof_cleaning"), stage:"pre_price", category:"required_to_price", requiredWhen:"an applicable square-foot service is selected", acceptedValues:[1,2,3], validation:"enum", pricingDestination:"homeDetails.stories", changesPrice:true, recapRequired:true, verifiedValueAllowed:true, derivedValueAllowed:true, missingBehavior:"missing_information", approvalStatus:"approved_current_behavior" },
  { fieldId:"condition", storagePath:"condition", appliesToServices:all("window_cleaning"), stage:"pre_price", category:"required_by_current_product_policy", requiredWhen:"standard whole-home window cleaning", acceptedValues:["maintenance","heavy"], validation:"enum", pricingDestination:"homeDetails.condition", changesPrice:true, recapRequired:true, verifiedValueAllowed:true, derivedValueAllowed:false, missingBehavior:"missing_information", approvalStatus:"approved_current_behavior", legacyAliases:["windowCleaningCondition"] },
  ...(["hardWaterStains","frenchPanes","ladderWork"] as const).map((fieldId): CanonicalIntakeField => ({ fieldId, storagePath:fieldId, appliesToServices:all("window_cleaning"), stage:"pre_price", category:"conditional_price_modifier", requiredWhen:"customer indicates applicable advanced window condition", validation:"existing web values", pricingDestination:`homeDetails.${fieldId}`, changesPrice:true, recapRequired:true, verifiedValueAllowed:true, derivedValueAllowed:false, missingBehavior:"omit_modifier", approvalStatus:"pending_ben_review" })),
  ...(["hardWaterPercent","frenchPanesPercent"] as const).map((fieldId): CanonicalIntakeField => ({ fieldId, storagePath:fieldId, appliesToServices:all("window_cleaning"), stage:"pre_price", category:"conditional_price_modifier", requiredWhen:`${fieldId.replace("Percent", "")} is explicitly selected`, acceptedValues:"configured percentage range", validation:"finite configured percentage", pricingDestination:`homeDetails.${fieldId}`, changesPrice:true, recapRequired:true, verifiedValueAllowed:true, derivedValueAllowed:false, missingBehavior:"missing_information", approvalStatus:"pending_ben_review" })),
  { fieldId:"ladderWorkCount", storagePath:"ladderWorkCount", appliesToServices:all("window_cleaning"), stage:"pre_price", category:"conditional_price_modifier", requiredWhen:"ladderWork is explicitly selected", acceptedValues:"positive integer", validation:"positive integer", pricingDestination:"homeDetails.ladderWorkCount", changesPrice:true, recapRequired:true, verifiedValueAllowed:true, derivedValueAllowed:false, missingBehavior:"missing_information", approvalStatus:"pending_ben_review" },
  { fieldId:"screenProfile", storagePath:"screenProfile", appliesToServices:all("window_cleaning"), stage:"pre_price", category:"required_by_current_product_policy", requiredWhen:"whole-home residential window cleaning selected", acceptedValues:["standard_removable","no_screens","solar","mixed_standard_solar","fixed_nonremovable_or_unknown"], validation:"enum", pricingDestination:"homeDetails.screenProfile plus provenance", changesPrice:true, recapRequired:true, verifiedValueAllowed:true, derivedValueAllowed:false, missingBehavior:"missing_information", approvalStatus:"confirmed_owner_rule", canonicalPrompt:"Which best describes the window screens at this home: standard removable screens, no screens, solar screens, a mix of standard and solar screens, or fixed/non-removable/unknown screens?" },
  { fieldId:"screenProfileProvenance", storagePath:"screenProfileProvenance", appliesToServices:all("window_cleaning"), stage:"pre_price", category:"derived_from_verified_source", requiredWhen:"screenProfile is captured", acceptedValues:["captured","verified","corrected","derived","defaulted","unanswered","unknown"], normalization:"derive from the canonical field-status record; reject independent customer writes", validation:"field-status enum", pricingDestination:"homeDetails.screenProfileProvenance", changesPrice:true, recapRequired:false, verifiedValueAllowed:false, derivedValueAllowed:true, missingBehavior:"omit_modifier", approvalStatus:"confirmed_owner_rule", deprecationNotes:"A missing or non-explicit provenance cannot activate the no-screen discount." },
  { fieldId:"solarScreenCoverage", storagePath:"solarScreenCoverage", appliesToServices:all("window_cleaning"), stage:"pre_price", category:"conditional_price_modifier", requiredWhen:"screenProfile is solar or mixed_standard_solar", acceptedValues:["all","some"], validation:"enum", pricingDestination:"homeDetails.solarScreenCoverage", changesPrice:true, recapRequired:true, verifiedValueAllowed:true, derivedValueAllowed:false, missingBehavior:"missing_information", approvalStatus:"approved_current_behavior", canonicalPrompt:"Do solar screens cover all windows or only some windows?", explanatoryCopy:"Solar screens are the large, dark screens that cover most or all of the window and block sunlight, making the glass difficult to see through from outside." },
  { fieldId:"solarScreenAffectedWindowCount", storagePath:"solarScreenAffectedWindowCount", appliesToServices:all("window_cleaning"), stage:"pre_price", category:"conditional_price_modifier", requiredWhen:"solarScreenCoverage is some", acceptedValues:"positive integer", validation:"positive integer", pricingDestination:"homeDetails.solarScreenAffectedWindowCount", changesPrice:true, recapRequired:true, verifiedValueAllowed:true, derivedValueAllowed:false, missingBehavior:"clarification", manualReviewBehavior:"current whole-home architecture cannot allocate a partial surcharge accurately", approvalStatus:"approved_current_behavior", canonicalPrompt:"How many windows have solar screens?" },
  { fieldId:"solarScreenServiceRequested", storagePath:"solarScreenServiceRequested", appliesToServices:all("window_cleaning"), stage:"pre_price", category:"optional_addon", requiredWhen:"solar screens are present", acceptedValues:[true,false], validation:"boolean", pricingDestination:"homeDetails.solarScreenServiceRequested", changesPrice:true, recapRequired:true, verifiedValueAllowed:true, derivedValueAllowed:false, missingBehavior:"omit_modifier", approvalStatus:"approved_current_behavior", canonicalPrompt:"Would you like those solar screens removed, cleaned, and reinstalled?" },
  { fieldId:"legacySolarScreens", storagePath:"solarScreens", appliesToServices:all("window_cleaning"), stage:"pre_price", category:"not_applicable", requiredWhen:"legacy persisted records only", validation:"legacy boolean plus solarScreensPercent", pricingDestination:"legacy homeDetails solar fields", changesPrice:true, recapRequired:false, verifiedValueAllowed:false, derivedValueAllowed:false, missingBehavior:"never_write_new", approvalStatus:"deprecated", legacyAliases:["solarScreens","solarScreensPercent"], deprecationNotes:"Normalize new intake to screenProfile/coverage/count/serviceRequested; retained read-only for persisted records." },
  { fieldId:"legacySunroom", storagePath:"sunroom", appliesToServices:all("window_cleaning"), stage:"pre_price", category:"not_applicable", requiredWhen:"legacy persisted records only", validation:"legacy size bucket", pricingDestination:"legacy window_addons.sunroom", changesPrice:true, recapRequired:false, verifiedValueAllowed:false, derivedValueAllowed:false, missingBehavior:"never_write_new", approvalStatus:"deprecated", legacyAliases:["sunroom"], deprecationNotes:"Replaced for new intake by enclosedPatioProfile plus screened soft-wash or per-window enclosure pricing." },
  { fieldId:"enclosedPatioProfile", storagePath:"enclosedPatioProfile", appliesToServices:all("window_cleaning","house_wash"), stage:"pre_price", category:"required_by_current_product_policy", requiredWhen:"window cleaning or house washing selected", acceptedValues:["none","screened","window_enclosed","mixed_or_uncertain"], validation:"enum", changesPrice:true, recapRequired:true, verifiedValueAllowed:true, derivedValueAllowed:false, missingBehavior:"missing_information", manualReviewBehavior:"mixed_or_uncertain requests clarification", approvalStatus:"approved_current_behavior", canonicalPrompt:"Does the home have no enclosed patio, a primarily screened enclosure, a primarily window-enclosed patio or sunroom, or a mixed/uncertain enclosure?" },
  { fieldId:"screenedEnclosureSoftWash", storagePath:"screenedEnclosureSoftWash", appliesToServices:all("window_cleaning","house_wash"), stage:"pre_price", category:"optional_addon", requiredWhen:"enclosedPatioProfile is screened", acceptedValues:[true,false], validation:"boolean", pricingDestination:"screened_enclosure_soft_wash line item", changesPrice:true, recapRequired:true, verifiedValueAllowed:true, derivedValueAllowed:false, missingBehavior:"omit_addon", approvalStatus:"approved_current_behavior", canonicalPrompt:"Would you like the screened enclosure soft washed?" },
  { fieldId:"enclosureWindowCount", storagePath:"enclosureWindowCount", appliesToServices:all("window_cleaning"), stage:"pre_price", category:"conditional_price_modifier", requiredWhen:"enclosedPatioProfile is window_enclosed", acceptedValues:"positive integer", validation:"positive integer", pricingDestination:"enclosure_window_cleaning quantity", changesPrice:true, recapRequired:true, verifiedValueAllowed:true, derivedValueAllowed:false, missingBehavior:"missing_information", approvalStatus:"approved_current_behavior", canonicalPrompt:"How many additional enclosure windows need cleaning?" },
  { fieldId:"enclosureWindowSides", storagePath:"enclosureWindowSides", appliesToServices:all("window_cleaning"), stage:"pre_price", category:"conditional_price_modifier", requiredWhen:"enclosedPatioProfile is window_enclosed", acceptedValues:["outside_only","inside_and_outside"], validation:"enum", pricingDestination:"enclosure_window_cleaning unit rate", changesPrice:true, recapRequired:true, verifiedValueAllowed:true, derivedValueAllowed:false, missingBehavior:"missing_information", approvalStatus:"approved_current_behavior", canonicalPrompt:"Should those enclosure windows receive exterior-only or inside-and-out cleaning?" },
  { fieldId:"windowCount", storagePath:"windowCount", appliesToServices:all("partial_window_cleaning","window_promo_99"), stage:"pre_price", category:"required_to_price", requiredWhen:"partial or promotion path selected", acceptedValues:"positive integer", validation:"positive integer plus configured promotion maximum", pricingDestination:"partial input or promotion.windowCount", changesPrice:true, recapRequired:true, verifiedValueAllowed:true, derivedValueAllowed:false, missingBehavior:"missing_information", approvalStatus:"approved_current_behavior" },
  { fieldId:"partialWindowPricingPolicy", storagePath:"humanPricingRequired", appliesToServices:all("partial_window_cleaning"), stage:"pre_price", category:"manual_review_trigger", requiredWhen:"partial-window request selected without an authoritative configured partial-price path", validation:"manual review", changesPrice:false, recapRequired:false, verifiedValueAllowed:false, derivedValueAllowed:false, missingBehavior:"manual_review", manualReviewBehavior:"must not enter whole-home square-footage pricing", approvalStatus:"approved_current_behavior" },
  { fieldId:"promotionId", storagePath:"promotionId", appliesToServices:all("window_promo_99"), stage:"pre_price", category:"required_to_price", requiredWhen:"promotion explicitly selected", acceptedValues:"active configured promotion id", validation:"live pricing configuration", pricingDestination:"promotion.id", changesPrice:true, recapRequired:true, verifiedValueAllowed:false, derivedValueAllowed:true, missingBehavior:"missing_information", approvalStatus:"approved_current_behavior" },
  { fieldId:"houseWashStainType", storagePath:"houseWashStainType", appliesToServices:all("house_wash"), stage:"pre_price", category:"conditional_price_modifier", requiredWhen:"rust/irrigation staining applies", acceptedValues:["organic","rust"], validation:"enum", pricingDestination:"additionalServices.houseWashDetails.stainType", changesPrice:true, recapRequired:true, verifiedValueAllowed:true, derivedValueAllowed:false, missingBehavior:"omit_modifier", approvalStatus:"approved_current_behavior" },
  { fieldId:"houseWashPatioPricingMethod", storagePath:"houseWashPatios.pricingMethod", appliesToServices:all("house_wash"), stage:"pre_price", category:"optional_addon", requiredWhen:"front or back patio pressure washing is selected", acceptedValues:["simple_selection","exact_square_footage"], validation:"enum; methods are mutually exclusive", pricingDestination:"additionalServices.houseWashPatios.pricingMethod", changesPrice:true, recapRequired:true, verifiedValueAllowed:true, derivedValueAllowed:false, missingBehavior:"missing_information_for_addon", approvalStatus:"approved_current_behavior", canonicalPrompt:"Would you like front-patio pressure washing, back-patio pressure washing, or both?", explanatoryCopy:"Know the approximate square footage? Enter it for a more exact patio price." },
  { fieldId:"houseWashPatioSelections", storagePath:"houseWashPatios", appliesToServices:all("house_wash"), stage:"pre_price", category:"optional_addon", requiredWhen:"simple_selection method selected", acceptedValues:"frontSelected and/or backSelected boolean", validation:"at least one selected", pricingDestination:"house_wash_front_patio / house_wash_back_patio", changesPrice:true, recapRequired:true, verifiedValueAllowed:true, derivedValueAllowed:false, missingBehavior:"omit_addon", approvalStatus:"approved_current_behavior" },
  { fieldId:"houseWashFrontPatioSqft", storagePath:"houseWashPatios.frontSqft", appliesToServices:all("house_wash"), stage:"pre_price", category:"conditional_price_modifier", requiredWhen:"exact_square_footage method and front patio selected", acceptedValues:"positive plausible finite number", validation:"0 < sqft <= 100000", pricingDestination:"house_wash_front_patio quantity", changesPrice:true, recapRequired:true, verifiedValueAllowed:true, derivedValueAllowed:true, missingBehavior:"missing_information_for_addon", approvalStatus:"approved_current_behavior" },
  { fieldId:"houseWashBackPatioSqft", storagePath:"houseWashPatios.backSqft", appliesToServices:all("house_wash"), stage:"pre_price", category:"conditional_price_modifier", requiredWhen:"exact_square_footage method and back patio selected", acceptedValues:"positive plausible finite number", validation:"0 < sqft <= 100000", pricingDestination:"house_wash_back_patio quantity", changesPrice:true, recapRequired:true, verifiedValueAllowed:true, derivedValueAllowed:true, missingBehavior:"missing_information_for_addon", approvalStatus:"approved_current_behavior" },
  { fieldId:"houseWashWindowBundle", storagePath:"services", appliesToServices:all("house_wash","window_cleaning"), stage:"pre_price", category:"derived_from_verified_source", requiredWhen:"both qualifying services are selected", acceptedValues:"stable derived identifier house_wash_window_cleaning_bundle", validation:"apply once; never below zero", pricingDestination:"priceAdjustments", changesPrice:true, recapRequired:true, verifiedValueAllowed:true, derivedValueAllowed:true, missingBehavior:"derive_from_selected_services", approvalStatus:"confirmed_owner_rule" },
  { fieldId:"gutterUndergroundDrainCount", storagePath:"gutterAddons.undergroundDrains.count", appliesToServices:all("gutter_cleaning"), stage:"pre_price", category:"optional_addon", requiredWhen:"underground-drain clearing selected", acceptedValues:"exact non-negative integer", validation:"integer; unknown and legacy 4+ require clarification", pricingDestination:"underground_gutter_drain_clearing quantity", changesPrice:true, recapRequired:true, verifiedValueAllowed:true, derivedValueAllowed:false, missingBehavior:"missing_information_for_addon", approvalStatus:"approved_current_behavior", legacyAliases:["gutterUndergroundDrains"], canonicalPrompt:"How many underground drains or downspouts would you like us to clear?", disclosure:"Clearing covers ordinary clogs and debris; damaged, collapsed, root-intruded, disconnected, or inaccessible drainage may require separate repair or specialized work." },
  { fieldId:"gutterRepairNeeds", storagePath:"gutterAddons.repairNeeds", appliesToServices:all("gutter_cleaning"), stage:"pre_price", category:"optional_addon", requiredWhen:"customer reports gutter/downspout repair needs", acceptedValues:["leaking_seams","loose_gutter_sections","detached_gutter_sections","loose_downspouts","detached_downspouts","none","unsure","another_repair_need"], validation:"deduplicated enum array", pricingDestination:"minor_gutter_downspout_repairs adjustment or repair-only clarification", changesPrice:true, recapRequired:true, verifiedValueAllowed:true, derivedValueAllowed:false, missingBehavior:"omit_addon", manualReviewBehavior:"unsure/another/contradictory needs route only repair portion to clarification", approvalStatus:"approved_current_behavior", legacyAliases:["gutterMinorRepairs"], canonicalPrompt:"Do you know of any leaking seams, loose or detached gutter sections, loose or detached downspouts, no repair needs, or another/uncertain repair need?" },
  { fieldId:"gutterRepairNotes", storagePath:"gutterAddons.repairNotes", appliesToServices:all("gutter_cleaning"), stage:"pre_price", category:"optional_addon", requiredWhen:"another_repair_need selected", acceptedValues:"customer text; optional photo reference", validation:"bounded text", changesPrice:false, recapRequired:true, verifiedValueAllowed:true, derivedValueAllowed:false, missingBehavior:"clarification", approvalStatus:"approved_current_behavior" },
  { fieldId:"gutterGuardsLinearFeet", storagePath:"gutterAddons.gutterGuards.linearFeet", appliesToServices:all("gutter_cleaning"), stage:"pre_price", category:"optional_addon", requiredWhen:"gutter guards selected", acceptedValues:"positive finite number", validation:"positive finite", pricingDestination:"additionalServices.gutterAddons.gutterGuards.linearFeet", changesPrice:true, recapRequired:true, verifiedValueAllowed:true, derivedValueAllowed:true, missingBehavior:"missing_information", approvalStatus:"pending_ben_review" },
  { fieldId:"roofType", storagePath:"roofType", appliesToServices:all("roof_cleaning"), stage:"pre_price", category:"owner_decision_required", requiredWhen:"roof cleaning selected", acceptedValues:["asphalt","tile","metal","flat"], validation:"enum", pricingDestination:"additionalServices.roofType", changesPrice:true, recapRequired:true, verifiedValueAllowed:true, derivedValueAllowed:true, missingBehavior:"owner_decision", approvalStatus:"pending_ben_review" },
  { fieldId:"roofSeverity", storagePath:"roofSeverity", appliesToServices:all("roof_cleaning"), stage:"pre_price", category:"owner_decision_required", requiredWhen:"roof cleaning selected", acceptedValues:["light","moderate","heavy"], validation:"enum", pricingDestination:"additionalServices.roofSeverity", changesPrice:true, recapRequired:true, verifiedValueAllowed:true, derivedValueAllowed:false, missingBehavior:"owner_decision", approvalStatus:"pending_ben_review" },
  { fieldId:"drivewaySqft", storagePath:"drivewaySqft", appliesToServices:all("driveway_cleaning"), stage:"pre_price", category:"required_to_price", requiredWhen:"driveway selected", acceptedValues:"positive finite number", validation:"positive finite", pricingDestination:"additionalServices.drivewayCleaning.sqft", changesPrice:true, recapRequired:true, verifiedValueAllowed:true, derivedValueAllowed:true, missingBehavior:"missing_information", approvalStatus:"approved_current_behavior" },
  { fieldId:"drivewaySurface", storagePath:"drivewaySurface", appliesToServices:all("driveway_cleaning"), stage:"pre_price", category:"required_to_price", requiredWhen:"driveway selected", acceptedValues:["concrete","stamped","pavers","brick","stone","tile"], validation:"enum", pricingDestination:"additionalServices.drivewayCleaning.surfaceType", changesPrice:true, recapRequired:true, verifiedValueAllowed:true, derivedValueAllowed:false, missingBehavior:"missing_information", approvalStatus:"approved_current_behavior" },
  { fieldId:"pressureWashingSurface", storagePath:"pressureWashSurface", appliesToServices:all("pressure_washing"), stage:"pre_price", category:"required_to_price", requiredWhen:"pressure washing selected", acceptedValues:["concrete","stamped","pavers","brick","stone","tile"], validation:"enum", pricingDestination:"additionalServices.pressureWashing.surfaceType", changesPrice:true, recapRequired:true, verifiedValueAllowed:true, derivedValueAllowed:false, missingBehavior:"missing_information", approvalStatus:"approved_current_behavior" },
  { fieldId:"pressureWashingAreas", storagePath:"pressureWashingAreas", appliesToServices:all("pressure_washing"), stage:"pre_price", category:"required_to_price", requiredWhen:"pressure washing selected", acceptedValues:"one or more enabled named areas with positive sqft", validation:"frontPorch/backPatio/poolDeck/walkways; at least one valid", pricingDestination:"additionalServices.pressureWashing named areas", changesPrice:true, recapRequired:true, verifiedValueAllowed:true, derivedValueAllowed:true, missingBehavior:"missing_information", manualReviewBehavior:"invalid enabled area is manual review in pricing engine", approvalStatus:"approved_current_behavior", legacyAliases:["pressureWashSqft"] },
  { fieldId:"solarPanelCount", storagePath:"solarPanelCount", appliesToServices:all("solar_panel_cleaning"), stage:"pre_price", category:"required_to_price", requiredWhen:"solar panel cleaning selected", acceptedValues:"integer 1..500", validation:"pricing-engine range", pricingDestination:"additionalServices.solarPanelCleaning.panelCount", changesPrice:true, recapRequired:true, verifiedValueAllowed:true, derivedValueAllowed:false, missingBehavior:"missing_information", approvalStatus:"approved_current_behavior" },
  { fieldId:"solarPanelPolicy", storagePath:"humanPricingRequired", appliesToServices:all("solar_panel_cleaning"), stage:"pre_price", category:"owner_decision_required", requiredWhen:"solar selected", validation:"explicit policy resolution", changesPrice:false, recapRequired:false, verifiedValueAllowed:false, derivedValueAllowed:false, missingBehavior:"owner_decision", manualReviewBehavior:"channel must not infer approval from engine firmness", approvalStatus:"pending_ben_review" },
  { fieldId:"screenRepairCount", storagePath:"screenRepairCount", appliesToServices:all("screen_repair"), stage:"pre_price", category:"required_to_price", requiredWhen:"screen repair selected", acceptedValues:"integer 1..500", validation:"pricing-engine range", pricingDestination:"additionalServices.screenRepair.screenCount", changesPrice:true, recapRequired:true, verifiedValueAllowed:true, derivedValueAllowed:false, missingBehavior:"missing_information", approvalStatus:"approved_current_behavior" },
  { fieldId:"screenRepairPolicy", storagePath:"humanPricingRequired", appliesToServices:all("screen_repair"), stage:"pre_price", category:"owner_decision_required", requiredWhen:"screen repair selected", validation:"explicit policy resolution", changesPrice:false, recapRequired:false, verifiedValueAllowed:false, derivedValueAllowed:false, missingBehavior:"owner_decision", manualReviewBehavior:"channel must not infer approval from engine firmness", approvalStatus:"pending_ben_review" },
  { fieldId:"commercialLocations", storagePath:"commercialLocations", appliesToServices:all("commercial_window_bid"), stage:"pre_price", category:"required_by_current_product_policy", requiredWhen:"commercial request", validation:"at least one structured location", changesPrice:false, recapRequired:true, verifiedValueAllowed:true, derivedValueAllowed:false, missingBehavior:"missing_information", approvalStatus:"approved_current_behavior" },
  { fieldId:"commercialPricingPolicy", storagePath:"humanPricingRequired", appliesToServices:all("commercial_window_bid"), stage:"pre_price", category:"manual_review_trigger", requiredWhen:"commercial request", validation:"manual review", changesPrice:false, recapRequired:false, verifiedValueAllowed:false, derivedValueAllowed:false, missingBehavior:"manual_review", manualReviewBehavior:"commercial requests remain outside automated residential pricing", approvalStatus:"approved_current_behavior" },
  { fieldId:"contact_email", storagePath:"email", appliesToServices:all("window_cleaning","partial_window_cleaning","window_promo_99","house_wash","gutter_cleaning","roof_cleaning","driveway_cleaning","pressure_washing","solar_panel_cleaning","screen_repair","commercial_window_bid"), stage:"post_price_delivery", category:"required_after_price_for_delivery", requiredWhen:"save/deliver or book", validation:"email", changesPrice:false, recapRequired:false, verifiedValueAllowed:true, derivedValueAllowed:false, missingBehavior:"block_delivery", approvalStatus:"approved_current_behavior" },
  { fieldId:"address", storagePath:"address", appliesToServices:all("window_cleaning","partial_window_cleaning","window_promo_99","house_wash","gutter_cleaning","roof_cleaning","driveway_cleaning","pressure_washing","solar_panel_cleaning","screen_repair","commercial_window_bid"), stage:"post_price_booking", category:"required_after_price_for_booking", requiredWhen:"availability or booking", validation:"authorized service address", changesPrice:false, recapRequired:false, verifiedValueAllowed:true, derivedValueAllowed:false, missingBehavior:"block_booking", approvalStatus:"approved_current_behavior" },
] as const;

const SERVICE_ALIASES: Readonly<Record<string, CanonicalServiceId>> = Object.freeze({
  windowCleaning:"window_cleaning", window_cleaning:"window_cleaning",
  houseWash:"house_wash", house_wash:"house_wash",
  gutters:"gutter_cleaning", gutterCleaning:"gutter_cleaning", gutter_cleaning:"gutter_cleaning",
  roofCleaning:"roof_cleaning", roof_cleaning:"roof_cleaning",
  driveway:"driveway_cleaning", drivewayCleaning:"driveway_cleaning", driveway_cleaning:"driveway_cleaning",
  pressureWashing:"pressure_washing", pressure_washing:"pressure_washing",
  solarPanelCleaning:"solar_panel_cleaning", solar_panel_cleaning:"solar_panel_cleaning",
  screenRepair:"screen_repair", screen_repair:"screen_repair",
});
export function normalizeServiceId(raw: string): CanonicalServiceId | null { return SERVICE_ALIASES[raw] ?? null; }
export function normalizeWindowCleaningSides(raw: unknown): CanonicalWindowSides | null {
  if (raw === "outside_only" || raw === "exterior") return "outside_only";
  if (raw === "inside_and_outside" || raw === "both") return "inside_and_outside";
  return null;
}
export function windowSidesToPricingType(sides: unknown): "exterior" | "both" | null {
  const normalized = normalizeWindowCleaningSides(sides);
  return normalized === "outside_only" ? "exterior" : normalized === "inside_and_outside" ? "both" : null;
}

function present(v: unknown): boolean { return v !== undefined && v !== null && v !== "" && (!Array.isArray(v) || v.length > 0); }
function valueAtPath(values: IntakeValues, path: string): unknown {
  return path.split(".").reduce<unknown>((current, key) =>
    current && typeof current === "object" ? (current as Record<string, unknown>)[key] : undefined, values);
}
function servicesFor(values: IntakeValues): CanonicalServiceId[] {
  if (values.windowCleaningScope === "partial") return ["partial_window_cleaning"];
  if (values.windowCleaningScope === "commercial_custom" || values.customerType === "commercial") return ["commercial_window_bid"];
  const out = ((values.services as string[] | undefined) ?? []).map(normalizeServiceId).filter((v): v is CanonicalServiceId => !!v);
  if (present(values.promotionId)) return ["window_promo_99"];
  return [...new Set(out)];
}
export interface IntakeEvaluation { services: CanonicalServiceId[]; requiredToPrice: string[]; productPolicyRequired: string[]; ownerDecisions: string[]; manualReview: string[]; deliveryRequired: string[]; bookingRequired: string[]; }
export function evaluateQuoteIntake(values: IntakeValues): IntakeEvaluation {
  const services = servicesFor(values);
  if (services.length === 0) return { services, requiredToPrice:["services"], productPolicyRequired:[], ownerDecisions:[], manualReview:[], deliveryRequired:[], bookingRequired:[] };
  const required = new Set<string>(); const policy = new Set<string>(); const decisions = new Set<string>(); const review = new Set<string>();
  for (const service of services) for (const f of CANONICAL_INTAKE_FIELDS) if (f.appliesToServices.includes(service)) {
    if (f.category === "required_to_price" && f.fieldId !== "services" && f.fieldId !== "windowCleaningSides" && !present(valueAtPath(values, f.storagePath))) required.add(f.fieldId);
    if (f.category === "required_by_current_product_policy" && !present(valueAtPath(values, f.storagePath))) policy.add(f.fieldId);
    if (f.category === "owner_decision_required" &&
      (f.fieldId.endsWith("Policy") || !present(valueAtPath(values, f.storagePath)))) decisions.add(f.fieldId);
    if (f.category === "manual_review_trigger") review.add(f.fieldId);
  }
  if ((services.includes("window_cleaning") || services.includes("partial_window_cleaning")) && !normalizeWindowCleaningSides(values.windowCleaningSides ?? values.windowCleaningType)) required.add("windowCleaningSides");
  if (services.includes("pressure_washing")) {
    const areas = values.pressureWashingAreas as Record<string,{enabled?:boolean;sqft?:number}> | undefined;
    const valid = areas && Object.values(areas).some(a => a?.enabled && Number.isFinite(a.sqft) && (a.sqft ?? 0) > 0);
    if (!valid) required.add("pressureWashingAreas");
  }
  if (services.includes("window_cleaning")) {
    if (values.hardWaterStains === true && !present(values.hardWaterPercent)) required.add("hardWaterPercent");
    if (values.frenchPanes === true && !present(values.frenchPanesPercent)) required.add("frenchPanesPercent");
    if (values.ladderWork === true && !present(values.ladderWorkCount)) required.add("ladderWorkCount");
    if (values.enclosedPatioProfile === "window_enclosed") {
      if (typeof values.enclosureWindowCount !== "number" || !Number.isInteger(values.enclosureWindowCount) || values.enclosureWindowCount <= 0) required.add("enclosureWindowCount");
      if (values.enclosureWindowSides !== "outside_only" && values.enclosureWindowSides !== "inside_and_outside") required.add("enclosureWindowSides");
    }
    if (values.screenProfile === "solar" || values.screenProfile === "mixed_standard_solar") {
      if (values.solarScreenCoverage !== "all" && values.solarScreenCoverage !== "some") required.add("solarScreenCoverage");
      if (values.solarScreenCoverage === "some" && (typeof values.solarScreenAffectedWindowCount !== "number" || !Number.isInteger(values.solarScreenAffectedWindowCount) || values.solarScreenAffectedWindowCount <= 0)) {
        required.add("solarScreenAffectedWindowCount");
      }
      if (values.solarScreenServiceRequested === true && values.solarScreenCoverage === "some") review.add("partialSolarScreenServiceClarification");
    }
    if (values.solarScreenServiceRequested === true && values.screenProfile === "fixed_nonremovable_or_unknown") review.add("fixedScreenServiceClarification");
  }
  if ((services.includes("window_cleaning") || services.includes("house_wash")) && values.enclosedPatioProfile === "mixed_or_uncertain") {
    review.add("enclosedPatioClarification");
  }
  if (services.includes("gutter_cleaning")) {
    const addons = values.gutterAddons as Record<string, unknown> | undefined;
    const drains = addons?.undergroundDrains as {enabled?:boolean;count?:unknown} | undefined;
    const guards = addons?.gutterGuards as {enabled?:boolean;linearFeet?:unknown} | undefined;
    const drainCount = typeof drains?.count === "string" && /^[0-9]+$/.test(drains.count) ? Number(drains.count) : drains?.count;
    if (drains?.enabled && (typeof drainCount !== "number" || !Number.isInteger(drainCount) || drainCount < 0)) required.add("gutterUndergroundDrainCount");
    const repairNeeds = Array.isArray(addons?.repairNeeds) ? addons.repairNeeds : [];
    if (repairNeeds.includes("unsure") || repairNeeds.includes("another_repair_need")) review.add("gutterRepairClarification");
    if (guards?.enabled && (typeof guards.linearFeet !== "number" || guards.linearFeet <= 0)) required.add("gutterGuardsLinearFeet");
  }
  if (services.includes("house_wash")) {
    const patios = values.houseWashPatios as Record<string, unknown> | undefined;
    const patioRequested = !!patios && (patios.frontSelected === true || patios.backSelected === true ||
      (typeof patios.frontSqft === "number" && patios.frontSqft > 0) || (typeof patios.backSqft === "number" && patios.backSqft > 0));
    if (patioRequested && patios?.pricingMethod !== "simple_selection" && patios?.pricingMethod !== "exact_square_footage") required.add("houseWashPatioPricingMethod");
    if (patios?.pricingMethod === "exact_square_footage") {
      if (patios.frontSelected === true && (typeof patios.frontSqft !== "number" || patios.frontSqft <= 0)) required.add("houseWashFrontPatioSqft");
      if (patios.backSelected === true && (typeof patios.backSqft !== "number" || patios.backSqft <= 0)) required.add("houseWashBackPatioSqft");
    }
  }
  return { services, requiredToPrice:[...required], productPolicyRequired:[...policy], ownerDecisions:[...decisions], manualReview:[...review], deliveryRequired:present(values.email)?[]:["contact_email"], bookingRequired:present(values.address)?[]:["address"] };
}
