// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-services.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var SERVICES = [
  {
    key: "window_cleaning",
    name: "Window Cleaning",
    description: "Interior and exterior window cleaning, priced per square foot with story and condition modifiers."
  },
  {
    key: "gutter_cleaning",
    name: "Gutter Cleaning",
    description: "Gutter cleanout with optional underground drain flushing, minor repairs, and micro-mesh gutter guards."
  },
  {
    key: "roof_cleaning",
    name: "Roof Cleaning",
    description: "Soft-wash roof cleaning priced per square foot with roof type and severity modifiers."
  },
  {
    key: "house_wash",
    name: "House Wash",
    description: "Exterior house soft-washing priced per square foot, with a surcharge for rust and irrigation stains."
  },
  {
    key: "driveway_cleaning",
    name: "Driveway Cleaning",
    description: "Pressure washing for driveways, priced per square foot by surface type."
  },
  {
    key: "pressure_washing",
    name: "Pressure Washing (Flatwork)",
    description: "Pressure washing for patios, walkways, and other flatwork, priced per square foot."
  }
];
var list_services_default = defineTool({
  name: "list_services",
  title: "List services",
  description: "List the home exterior cleaning services BluLadder offers, with a short description of each.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(SERVICES, null, 2) }],
    structuredContent: { services: SERVICES }
  })
});

// src/lib/mcp/tools/get-pricing-info.ts
import { createClient } from "npm:@supabase/supabase-js@^2.91.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function publicSupabase() {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var get_pricing_info_default = defineTool2({
  name: "get_pricing_info",
  title: "Get pricing info",
  description: "Return BluLadder's public pricing configuration (base rates, multipliers, minimums, and add-ons). Optionally filter by a config key such as 'window_base_rates' or 'story_multipliers'.",
  inputSchema: {
    config_key: z.string().optional().describe("Optional exact config key to return a single configuration entry.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ config_key }) => {
    const supabase = publicSupabase();
    let query = supabase.from("pricing_config").select("config_key, config_value, description");
    if (config_key) query = query.eq("config_key", config_key);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { pricing: data }
    };
  }
});

// src/lib/mcp/tools/get-booking-link.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var APP_URL = "https://bluladderbid.lovable.app";
var SERVICE_KEYS = [
  "window_cleaning",
  "gutter_cleaning",
  "roof_cleaning",
  "house_wash",
  "driveway_cleaning",
  "pressure_washing"
];
var get_booking_link_default = defineTool3({
  name: "get_booking_link",
  title: "Get booking link",
  description: "Build a link to BluLadder's online booking / quote flow. Optionally pre-select a service and attach UTM attribution parameters.",
  inputSchema: {
    service: z2.string().optional().describe(
      "Optional service key to pre-select, e.g. window_cleaning, gutter_cleaning, roof_cleaning, house_wash, driveway_cleaning, pressure_washing."
    ),
    utm_source: z2.string().optional().describe("Optional UTM source for attribution."),
    utm_medium: z2.string().optional().describe("Optional UTM medium for attribution."),
    utm_campaign: z2.string().optional().describe("Optional UTM campaign for attribution.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ service, utm_source, utm_medium, utm_campaign }) => {
    const url = new URL(APP_URL + "/");
    if (service && SERVICE_KEYS.includes(service)) {
      url.searchParams.set("service", service);
    }
    if (utm_source) url.searchParams.set("utm_source", utm_source);
    if (utm_medium) url.searchParams.set("utm_medium", utm_medium);
    if (utm_campaign) url.searchParams.set("utm_campaign", utm_campaign);
    const link = url.toString();
    return {
      content: [{ type: "text", text: link }],
      structuredContent: { url: link }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "bluladder-mcp",
  title: "BluLadder",
  version: "0.1.0",
  instructions: "Tools for BluLadder, a home exterior cleaning company (window cleaning, gutters, roof, house wash, pressure washing). Use `list_services` to see what is offered, `get_pricing_info` to explain how pricing works, and `get_booking_link` to send a customer to the online booking/quote flow.",
  tools: [list_services_default, get_pricing_info_default, get_booking_link_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
