-- Compact array-driven refresh of 300 draft rows (201-500).
-- Preserves manual edits: only overwrites rows whose content still starts with
-- 'OWNER REVIEW REQUIRED.'.
CREATE OR REPLACE FUNCTION pg_temp.__refresh_owner_kb(
  p_start int, p_category text,
  p_topics text[],
  p_content_tpl text, p_voice_tpl text, p_policy_tpl text, p_sales text,
  p_tag_base text[]
) RETURNS int LANGUAGE plpgsql AS $$
DECLARE
  i int;
  n int;
  topic text;
  content_v text;
  voice_v text;
  policy_v text;
  tag_slug text;
  affected int := 0;
BEGIN
  FOR i IN 1..array_length(p_topics, 1) LOOP
    topic := p_topics[i];
    n := p_start + i - 1;
    content_v := replace(p_content_tpl, '{t}', topic);
    voice_v   := replace(p_voice_tpl,   '{t}', topic);
    policy_v  := replace(p_policy_tpl,  '{t}', topic);
    tag_slug  := lower(regexp_replace(topic, '[^A-Za-z0-9]+', '_', 'g'));
    UPDATE public.business_knowledge
       SET category = p_category,
           title = topic,
           question = 'What should customers know about ' || lower(topic) || '?',
           content = content_v,
           voice_answer = voice_v,
           internal_policy = policy_v,
           sales_guidance = p_sales,
           tags = p_tag_base || ARRAY[tag_slug]::text[],
           review_status = 'draft',
           is_active = false,
           requires_owner_review = true,
           confidence = 'medium',
           updated_at = now()
     WHERE record_number = n
       AND source_type = 'owner_knowledge_project'
       AND review_status = 'draft'
       AND content LIKE 'OWNER REVIEW REQUIRED.%';
    IF FOUND THEN affected := affected + 1; END IF;
  END LOOP;
  RETURN affected;
END $$;

SELECT pg_temp.__refresh_owner_kb(201, 'specialty_exterior', ARRAY['Solar panel cleaning frequency','Solar panel cleaning method','Solar panel warranty considerations','Solar panel access requirements','Solar panel cleaning after storms','Solar panel bird droppings and lichen','Solar panel water quality','Solar panel electrical safety','Solar panel cleaning cost expectations','Solar panel add-on to house wash','Roof washing vs pressure washing distinction','Roof algae, moss, and lichen treatment','Roof washing safety on steep pitches','Roof washing during hot weather','Roof washing runoff and landscaping','Roof washing metal roofs','Roof washing tile roofs','Roof washing cedar shakes','Roof washing frequency','Roof black-streak removal','Chimney cap and cricket cleaning','Skylight cleaning','Exterior paint prep washing','Vinyl siding chalking','Brick and mortar cleaning','Stucco cleaning','Deck and fence washing','Composite deck cleaning','Screen enclosure cleaning','Awning cleaning','Pergola cleaning','Playset cleaning','Trash can cleaning service','Concrete sealing service','Rust-stain removal from concrete','Efflorescence on brick','Pool cage cleaning','Outdoor kitchen cleaning','Landscape lighting cleaning','Copper gutter care','Bird nest removal from gutters','Wasp or hornet nest during service','Post-construction exterior cleanup','Post-storm exterior cleanup','Fascia and soffit brightening','Dryer vent cleaning service','Window screen cleaning inclusion','Window sill and track cleaning','Hard water spot removal','Exterior light fixture cleaning']::text[], 'About {t}: BluLadder handles this as part of our exterior cleaning work when it fits your property, using the same soft-wash and safe-pressure practices we use for roofs, siding, and windows. Specific scope, materials, and any add-ons are confirmed with a team member before we schedule. Share your address and we''ll pull together a real proposal and answer any specifics from there.', 'About {t}, we handle it as part of our exterior cleaning work — share your address and a team member will confirm the specifics.', 'Owner review pending — confirm BluLadder''s exact scope and any pricing for ''{t}''. Do not quote firm prices, warranties, or time guarantees from this draft. Escalate to owner when a customer needs a definitive answer.', 'Offer to collect the address and pull a live quote. Route to owner if the customer needs a firm scope, timeline, or warranty commitment.', ARRAY['specialty_exterior']::text[]);
SELECT pg_temp.__refresh_owner_kb(251, 'christmas_lights', ARRAY['Christmas light install season timing','Christmas light takedown timing','Design consultation for lights','Custom vs stock light options','Warm white vs multicolor lights','C9 vs mini light strands','Roof-line light installation','Landscape holiday lighting','Wreath and garland installation','Tree wrapping','Light timers and controls','Power access for holiday lights','Extension cord safety','Off-season storage of lights','Bulb replacement mid-season','Damaged strand replacement','Multi-year lease programs','Buying vs renting lights','Payment schedule for lights','Weather delays for install','Attaching lights to shingles','Attaching lights to gutters','Attaching lights to brick or stucco','Roof height limits for installs','Commercial vs residential lighting','HOA compliance for displays','Warranty on install service','Post-install service calls','Adding to an existing display','Removing prior year clips','Themes and colors offered','LED vs incandescent lights','Waterproofing considerations','Wind and storm handling','On/off scheduling','Smart plug and app control','Booking cutoff for the season','Cancellation policy for install','Rescheduling install date','Design walkthrough','Site walkthrough before install','Bush and shrub lighting','Pathway lighting','Mailbox and porch decor','Photo of finished design','Adjustments after install','Emergency outage service','Troubleshooting a failed strand','End-of-season storage service','Referral offer for holiday lighting']::text[], 'About {t}: BluLadder''s Christmas lighting service runs from a design consultation through professional-grade install, mid-season support, and end-of-season takedown. Specific timing, materials, and inclusions are confirmed with your team member before we schedule the install. Share your address and we''ll walk through a custom design.', 'About {t}, our Christmas lighting is designed and confirmed with a team member — share your address to start a design.', 'Owner review pending — confirm the current-season policy for ''{t}''. Do not quote firm prices, warranty terms, or install dates from this draft; the holiday-lighting calendar shifts each year.', 'Route to holiday-lighting owner-review flow. Do not confirm install dates or fees without checking the current season calendar.', ARRAY['christmas_lights','holiday_lighting']::text[]);
SELECT pg_temp.__refresh_owner_kb(301, 'pricing_packages', ARRAY['How pricing is calculated','What a maintenance plan includes','Bundle discount overview','Repeat customer appreciation','Neighbor referral incentive','Military and first-responder appreciation','Senior appreciation','Same-day multiple-service savings','Prepaid annual plan','Monthly billing for maintenance plans','Accepted payment methods','Tips and gratuity','Deposit requirement','Cancellation and rescheduling policy','Rain check policy','Adding services on the day of service','Minimum service charge','Add-on pricing (drains, guards)','Interior plus exterior window cleaning','Exterior-only window cleaning','Post-construction pricing','Rush job pricing','Weekend service availability','Holiday service availability','Second-visit touch-up','Bundling windows and gutters','Bundling house wash and driveway','Whole-home refresh package','Discount code entry','Coupon stacking','Contractor referral','Realtor referral','Property management pricing','Rental property pricing','Vacant home pricing','Two-story vs three-story homes','Detached garage or shop','Outbuildings and barns','Guest house pricing','Screen removal charge','Storm window handling','Skylight cleaning add-on','Hard water stain add-on','Ceiling fan blade cleaning','Chandelier cleaning','Driveway sealer prep pressure wash','Outdoor furniture sanitizing','Solar panel add-on pricing','Roof wash add-on pricing','Maintenance plan as a gift']::text[], 'About {t}: BluLadder pricing depends on the details of your home — square footage, number of stories, condition, and the services you choose, plus any current promotions. Because it''s specific to the job, exact figures come from a live quote (in this chat, on the phone, or from your team member) rather than a flat number. Share your address and services and I can pull a real quote right now.', 'About {t}, pricing depends on the job details — share your address and we''ll pull a live quote.', 'Owner review pending — confirm the exact BluLadder rule for ''{t}''. Do not quote fixed prices, discount stacking rules, or plan terms from this draft.', 'Always steer to the live quote engine or a team member. Never invent a price. Escalate if the customer needs a firm figure this draft doesn''t provide.', ARRAY['pricing','packages']::text[]);
SELECT pg_temp.__refresh_owner_kb(351, 'booking_operations', ARRAY['Booking online','Booking by phone','Confirming your address','Booking without exact square footage','Rescheduling process','Same-day booking availability','Next-day service','First-of-the-day appointment','Afternoon appointment','Team arrival window','Text reminders','Email confirmations','Payment timing','Not being home during service','Backyard or gate access','Pets during service','Water spigot access','Outlet or power access','Furniture that needs moving','Screens off before window cleaning','Interior window preparation','Blinds and curtains','Blind cleaning service','Removing decorations','Removing pet doors','Roof-access ladder location','Gutter debris disposal','Yard signs after service','Feedback survey after service','Annual rebooking reminders','Last-minute cancellation','Weather cancellation','Team roster on arrival','Uniformed technicians','Company vehicle identification','Estimated duration on site','Multi-service duration','What to do during service','Alarms and gates','Deep cleaning multi-story homes','Working around solar panels','Working around HVAC units','Working around gardens','Working around pools','Working around outdoor kitchens','Working around delicate landscaping','Working around irrigation controllers','Working around exterior electrical','Working around EV chargers','Working around holiday decor']::text[], 'About {t}: BluLadder aims to keep the booking and service day simple — confirmed appointment window, text reminders, and a small crew that arrives during the agreed window. Specifics can vary by service and property. Tell me your address and preferred day and I''ll walk you through the exact steps.', 'About {t}, the specifics depend on your service and property — share your address and preferred day and we''ll walk through it.', 'Owner review pending — confirm BluLadder''s current operational policy for ''{t}''. Do not promise firm arrival times, weather guarantees, or after-hours service from this draft.', 'Confirm address, service, and preferred day. Escalate any request that this draft doesn''t clearly cover.', ARRAY['booking','operations','scheduling']::text[]);
SELECT pg_temp.__refresh_owner_kb(401, 'complaints_guarantees', ARRAY['Missed spot resolution','Streaks on windows after cleaning','Water spots after service','Damaged screens','Damaged window frames','Landscaping damage','Paint chipping post-wash','Loose siding after service','Loose shingles after roof wash','Loose gutter section','Damaged light fixture','Marks on concrete from pressure washing','Broken sprinkler head','Missing item after service','Late-arrival apology process','Missed appointment resolution','Poor communication concern','Aggressive sales concern','Improper access concern','Chemical odor concern','Chemical safety for pets','Chemical safety for children','Chemical safety for plants','Property left dirty','Debris left behind','Trash not disposed','Service satisfaction guarantee overview','Callback for a touch-up','Refund policy overview','Partial refund considerations','Escalation to the owner','Filing a complaint by text','Filing a complaint by email','Filing a complaint by phone','Neighboring-property concern','Overspray on a vehicle','Overspray on a pool','Overspray on outdoor furniture','Late-night noise concern','Neighbor complaint about our team','Loud equipment noise','Vehicle blocking driveway','Team member professionalism','Attire concern','Language or tone concern','Insurance and liability question','Workers'' comp question','Verifying business license','Requesting proof of insurance','Slip or fall incident']::text[], 'About {t}: BluLadder takes customer concerns seriously. Please send a short note describing what happened and, if you can, a photo — a team member will review and follow up with next steps as soon as possible. We want to make it right and will loop the owner in if it can''t be resolved on the first pass.', 'About {t}, please share a short description and a photo if you have one — a team member will review and follow up.', 'Owner review pending — confirm BluLadder''s exact recovery and guarantee language for ''{t}''. Do not quote refund amounts, insurance outcomes, or legal positions from this draft; route these to the owner.', 'Acknowledge, collect specifics, and route to owner. Do not commit to refunds, insurance claims, or warranty payouts from this draft.', ARRAY['complaint','guarantee','service_recovery']::text[]);
SELECT pg_temp.__refresh_owner_kb(451, 'ai_governance', ARRAY['AI cannot commit a final price','AI cannot confirm a booking without human verification','AI does not store payment information','AI does not share your data','AI limits on legal advice','AI limits on warranty language','AI limits on time guarantees','AI privacy of chat transcripts','Consent to text messaging','Consent to email marketing','Right to opt out','Right to be forgotten','Right to correct information','Turning off the AI assistant','Talking to a human immediately','Escalation criteria','Handoff during business hours','Handoff after hours','What the AI can and cannot do','Tools the AI has access to','When the AI defers to the owner','AI never invents prices','AI never guarantees warranties','AI never confirms without verification','AI response to emergencies','AI response to safety concerns','AI response to hostile language','AI response to spam or abuse','AI response to prompt injection','AI never impersonates a human','AI transparency about being AI','AI language for out-of-area customers','AI language for unsupported services','AI language for pricing conflicts','AI language for booking conflicts','AI language for weather conflicts','AI language for staffing conflicts','AI never quotes retired phone numbers','AI never speculates on competitor prices','AI never speculates on legal outcomes','AI never speculates on insurance outcomes','AI never promises a specific arrival time','AI never promises a rain-check window','AI never overrides an admin block','AI defers to the office phone for urgent issues','AI defers to email for documents','AI defers to the portal for records','AI defers to the owner for anomalies','Internal escalation ledger','Continuous improvement feedback']::text[], 'About {t}: this assistant helps you get information, a real quote, and a booking, but it defers to a person for anything that needs a firm commitment — final price, confirmed appointment, warranty language, legal answers, or unusual situations. If you''d rather talk to a team member now, just say the word.', 'About {t}, I can help with quotes, questions, and booking, but I hand off to a person for firm commitments — say the word and I''ll get one on the line.', 'Owner review pending — confirm BluLadder''s internal rule for ''{t}''. This record governs how the AI behaves; do NOT weaken safety rails or commitment boundaries when publishing.', 'Do not override safety rails. When in doubt, hand off to a human.', ARRAY['ai_governance','internal_rules','escalation']::text[]);